### ISSUE TITLE
SSL Certs randomly not secure

### ISSUE THREAD

**Issue by SimplyCorbett** [jiangwenyuan/nuster#104]
I don't know how to reproduce this and I don't see any errors.

Problem:

With nuster v5.2.3.22 (may affect other versions) when browsing my website I randomly get SSL insecure warnings. These go away after several page refreshes.

Current setup:

WAN -> Gateway (Nuster) with forwardfor ssl enabled -> LAN -> Gateway (Nuster) without forwardfor and ssl is enabled -> Nginx with PHP-FPM ssl enabled.

Edit: See below for the full setup

Both gateways have seven SSL certificates loaded under bind *:443 with alpn h2,http/1.1
Both gateways use use acl rules to decide what domain goes to what backend.
This issue happens on domains with caching disabled and enabled.
Both gateways use server s1-s10 with ip:port and check ssl verify none.
Both gateways have stats enabled (http and socket)
Both gateways have mode http and option http-buffer-request enabled under defaults.
Both gateways have tune.ssl.default-dh-param 2048 in global.

Nuster is compiled with only openssl support.

**Comment by Dragon988** [comment]
Added in another domain and the entire thing basically died. Some weird errors about the master-worker crashing and then restarting on it's own but nothing that would point to the issue.

That was rare though. What actually happened was it just didn't serve domains:

WAN nuster saw the backends online Did not forward traffic back to the end user.

Reduced certs to 2, reduced backends to 3 - everything running smooth again.

**Comment by Dragon988** [comment]
It is a nuster issue but I'm not actually sure if it's due to my setup or not.

It's a little complex.

WAN -> 100TB dedicated server (Nuster) -> 10Gbps LAN (dedi host) -> Wireguard Gateway -> LAN (Nuster,home) -> Backends

**Comment by jiangwenyuan** [comment]
Can you share the config file? and more detailed error messages? what happens if you change nuster to haproxy v2.2.3?

**Comment by Dragon988** [comment]
I think this may be another case of user error. Seems to be okay now, but I'm not using all of the ssl certs yet.

I'll go ahead and close this. If it does happen again I'll reopen with more data.

**Comment by SimplyCorbett** [comment]
I ended up adding more domains and the issue returned. Is there something wrong with my configuration?

https://gist.github.com/SimplyCorbett/0cf9a27b60f9061f6b88b18c4c61c6ee

I ended up adding the ssl certificates to the backends to try combating this (they were not originally there).

I'm sure it's something with my configuration.

**Comment by SimplyCorbett** [comment]
Whoops, reopening.

**Comment by SimplyCorbett** [comment]
I've removed the two new certificates and it started working again.

**Comment by SimplyCorbett** [comment]
Okay, so it turns out if one ssl certificate is invalid it destroys the entire cluster. Or did in my case.

Glad I got that solved though.
