### ISSUE TITLE
缓存key中param_id 不生效

### ISSUE THREAD

**Issue by luger1990** [jiangwenyuan/nuster#105]
`nuster rule r1 key host.path.param_id. ttl 300s if { path_beg /api/xxx }` 这样配置缓存的key中没有`param_id`。是我配置的方式不对吗？
补充一下:我是用docker启动的

**Comment by jiangwenyuan** [comment]
@luger1990  请求是怎么样的？ /api/xxx?id=1234 ?

**Comment by luger1990** [comment]
> @luger1990 请求是怎么样的？ `/api/xxx?id=1234` ?

对的请求是这样的 我开启debug了 看到缓存的key没有param_id 如果缓存的key改为query 那么是可以的。

**Comment by jiangwenyuan** [comment]
是什么版本呀？

**Comment by jiangwenyuan** [comment]
@luger1990 fix了，push到master了。能麻烦看一看吗？

**Comment by luger1990** [comment]
> @luger1990 fix了，push到master了。也更新了docker。能麻烦看一看吗？

纳尼。。。这么大的bug 吓得我不敢用了😂😂😂

**Comment by luger1990** [comment]
继续支持 有问题我再继续反馈 先在公司小范围用一用 坐着加油方便的话加一下微信什么的

**Comment by jiangwenyuan** [comment]
> > @luger1990 fix了，push到master了。也更新了docker。能麻烦看一看吗？
> 
> 纳尼。。。这么大的bug 吓得我不敢用了😂😂😂

没有，就是param的解析部分上次优化时写错了一个变量名。

**Comment by jiangwenyuan** [comment]
> 继续支持 有问题我再继续反馈 先在公司小范围用一用 坐着加油方便的话加一下微信什么的

可以把微信号码发我邮件

**Comment by luger1990** [comment]
> > 继续支持 有问题我再继续反馈 先在公司小范围用一用 坐着加油方便的话加一下微信什么的
> 
> 可以把微信号码发我邮件

测试没问题了,给作者点个赞！加油。稍后把我的微信发到您的邮箱
