### ISSUE TITLE
How to donate to get technical support ？

### ISSUE THREAD

**Issue by Macolden** [jiangwenyuan/nuster#106]
How to donate to get technical support ？macolden@qq.com

**Comment by jiangwenyuan** [comment]
I'll take a look at Github Sponsorships. Anyway you can reach out by emailing me.

**Comment by Macolden** [comment]
江工程师：
冒昧打扰，我们准备用nuster编译搭建proxy+cache应用，计划先捐赠500元人民币，如果能稳定运行，3个月后再捐赠1000元
人民币，希望能提供编译安装、配置的技术支持；具体需求如下：
1、https://frontend1.abc,com 和frontend2负责访问接入,，
2、backend https://cache1.abc.com



At 2020-11-17 23:14:02, "Jiang Wenyuan" <notifications@github.com> wrote:

I'll take a look at Github Sponsorships. Anyway you can reach out by emailing me.

**Comment by Macolden** [comment]
江工程师：
冒昧打扰，我们准备用nuster编译搭建proxy+cache应用，计划先捐赠500元人民币，如果能稳定运行，3个月后再捐赠1000元
人民币，希望能提供编译安装、配置的技术支持；具体需求如下：
1、https://source.abc.com 动态交互服务器是nginx+php，html、jpg、png、json、js、mp4静态文件也在同一nginx server；安装Keepalived高可用 ;
2、我理解https://frontend1.abc.com 和 https://frontend2.abc.com负责访问接入, 安装Keepalived高可用 ;
3、https://cache1.abc.com、https://cache2.abc.com、117.59.126.73 配置为 backend；
还望江工能否提供编译部署步骤和相关配置文件说明？计划由重庆翰桥公司转款



At 2020-11-17 23:14:02, "Jiang Wenyuan" <notifications@github.com> wrote:

I'll take a look at Github Sponsorships. Anyway you can reach out by emailing me.
