### ISSUE TITLE
非标准的url格式会导致缓存失效

### ISSUE THREAD

**Issue by luger1990** [jiangwenyuan/nuster#107]
`http://domain//api/xxx/xxx?k=v`这样的url请求不会触发缓存策略。

问题是url中的 `//` 多了一个 `/`

**Comment by jiangwenyuan** [comment]
可以删除多余的 `/`

**Comment by luger1990** [comment]
但是还是希望nuster能兼容一下，因为无法保证第三方的调用都是规范的，只能发现后才告知
