### ISSUE TITLE
How do you define max memory when using disk?

### ISSUE THREAD

**Issue by SimplyCorbett** [jiangwenyuan/nuster#108]
In the example here it shows both disk and memory cache are enabled, but it only shows the max cache in memory.

https://github.com/jiangwenyuan/nuster/wiki/Use-nuster-As-HTTP-Cache-Server

Can you add to the documentation to explain how to configure say 3GB of memory as cache, followed with 60GB of disk cache when the memory gets full?

And would there be a way to define frequently accessed files get priority in memory?

**Comment by SimplyCorbett** [comment]
Disk sync mode is interesting but still not what I'm looking for since it only syncs from memory to disk.

**Comment by jiangwenyuan** [comment]
Hi, disk size is not supported yet(I've got many requests), nor the LRU

**Comment by SimplyCorbett** [comment]
Ah, okay then. Thank you!

**Comment by SimplyCorbett** [comment]
How does it handle running out of disk space then for cache?

**Comment by jiangwenyuan** [comment]
> How does it handle running out of disk space then for cache?

For existing disk cache: keep serving
For new responses: try to cache but will fail, so just acts like a LB
