### ISSUE TITLE
Can I use it with Wordpress?

### ISSUE THREAD

**Issue by robert1112** [jiangwenyuan/nuster#11]
Hi Is there easy way to use it with Ngxin and wordpress? Thank you.

**Comment by jiangwenyuan** [comment]
Hi,

Yes, you can use it with (Nginx and) wordpress, and I think the setup is quite easy.

**Comment by robert1112** [comment]
Hi @jiangwenyuan  
Nice to hear from you so soon! We got a HAProxy in the front of Nginx. And how will the user purge the cache from Wordpress directly from Wordpress dashboard without a wordpress plugin? Is there further caution/ advice I can take from you? Thank you.

**Comment by jiangwenyuan** [comment]
Hi @robert1112 

I'm not familiar with wordpress dashboard, basically purging cache is done by making HTTP `PURGE` or `POST` requests, as long as you can make HTTP request in dashboard, I think you can purge cache without plugin.

**Comment by robert1112** [comment]
Okay I will see it can be pulled off. Thank you so mcuh for your excellent work.

**Comment by jiangwenyuan** [comment]
Not at all, feel free to fire any issues
