### ISSUE TITLE
实际测试的性能，比作者说的差距非常大。结论：没有必须使用nuster，直接使用nginx就可以。

### ISSUE THREAD

**Issue by OpenMIS** [jiangwenyuan/nuster#111]
实际测试的性能，比作者说的差距非常大，在ssl访问静态页面方面性能远不如nginx，即使nuster已经命中内存缓存。
nuster配置：

`
global
  nbproc 1 #一个进程，跟nginx类似，跟CPU超线程数有关，可以优化性能。
  nbthread 4 #每个进程的线程数
  daemon
  master-worker
  nuster cache on data-size 50m dir /tmp/nuster-cache

  ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256 #此次参看 参看 Document\经验分享\互联网\证书.txt 12、服务端的证书配置 1）生成器SSL Configuration Generator
  ssl-default-bind-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
  ssl-default-bind-options ssl-min-ver TLSv1.2 #禁用一些不安全的协议

  ssl-default-server-ciphersuites ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
  ssl-default-server-ciphers ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
  ssl-default-server-options ssl-min-ver TLSv1.2 #禁用一些不安全的协议
   
  tune.maxaccept -1 #默认值跟操作系统有关
  tune.h2.max-concurrent-streams 1000 #默认值是100
  tune.bufsize 32768
  
  tune.ssl.default-dh-param 2048
  tune.ssl.lifetime 1d
  tune.ssl.cachesize 200000 #默认为20000块，1块为200字节。  

defaults
  mode                    http         #所处理的类别(7层代理http，4层代理tcp)
  retries                 3            #3次连接失败就认为服务器不可用，也可以通过后面设置
  option                  dontlognull  #不记录健康检查日志信息
  option                  redispatch   #《---上述选项意思是指serverID 对应的服务器挂掉后，强制定向到其他健康的服务器, 当使用了 cookie时，

 
  option                  abortonclose #当服务器负载很高的时候，自动结束掉当前队列处理比较久的连接
  timeout http-request    10s
  timeout queue           1m
  timeout connect         10s
  timeout client          1m
  timeout server          1m
  timeout http-keep-alive 120s #参看nginx的keepalive_timeout
  timeout check           10s
  maxconn                 30000       #最大连接数
  stats refresh 30       #设置统计页面刷新时间间隔
  http-reuse              always
  timeout check           10s  #设置心跳检查超时时间
  balance roundrobin      #设置默认负载均衡方式，轮询方式
  balance source          #设置默认负载均衡方式，类似于nginx的ip_hash

frontend fe
  bind *:80
  bind *:443 ssl crt /data/opt/ssl/sl266.com-ecc/all.pem alpn h2,http/1.1
  stats uri       /admin/stats
  option http-keep-alive
  default_backend be
  option clitcpka
  http-response set-header x-cache hit if { nuster.cache.hit }
  http-response add-header Connectio1 keep-aliv1
  http-request set-header Connection keep-alive
  redirect scheme https code 301 if !{ ssl_fc } #把http重定向到https

backend be
  nuster cache on
  nuster rule all ttl 0

  server s1 127.0.0.1:81 #check
  option http-keep-alive
  option http-pretend-keepalive
  option srvtcpka
  option forwardfor  
`

---------------------------------------------------------------------------------------------
nginx配置：

`
server {

  listen       81; #跟nuster前置服务器配合
  listen       444 http2 ssl; #端口

  server_name  localhost; #域名，多个用空格
  access_log  logs/default.access.log main; #访问日志，以及调用的日志格式

  root   /data/service-data/web/default; #网站根目录路径
  index  index.html index.htm; #欢迎（索引）页面

  #Let's Encrypt(certbot) 自动生成的证书ECC secp384r1，不含*子域名 begin -----------------------
  ssl_certificate /data/opt/ssl/sl266.com-ecc/fullchain.pem; #相对于conf目录，需要全链证书，这样可以兼容更多的客户端。
  ssl_certificate_key /data/opt/ssl/sl266.com-ecc/key.pem; #相对于conf目录
  #Let's Encrypt(certbot) 自动生成的证书ECC secp384r1，不含*子域名 end -----------------------

  #Let's Encrypt(certbot) 自动生成的证书RSA 2048位，不含*子域名 begin -----------------------
  ssl_certificate /etc/letsencrypt/live/sl266.com/fullchain.pem; #相对于conf目录，需要全链证书，这样可以兼容更多的客户端。
  ssl_certificate_key /etc/letsencrypt/live/sl266.com/privkey.pem; #相对于conf目录
  #Let's Encrypt(certbot) 自动生成的证书RSA 2048位，不含*子域名 end -----------------------

  #参考：
  #Nginx下配置高性能，高安全性的https TLS服务 http://www.tuicool.com/articles/mU7vqm

  ssl_session_timeout 1d;
  ssl_session_cache shared:SSL:50m;
  ssl_prefer_server_ciphers   on; # 协商时优先使用服务器指定的加密算法

  # HSTS (ngx_http_headers_module is required) (15768000 seconds = 6 months)
  add_header Strict-Transport-Security max-age=15768000;

  # OCSP Stapling ---
  # fetch OCSP records from URL in ssl_certificate and cache them
  #ssl_stapling on;
  #ssl_stapling_verify on;	

  #参考：
  #Nginx服务器中关于SSL的安全配置详解【重点】 http://www.jb51.net/article/68452.htm
  #【重点】参看certbot生成的SSL参数 LinuxInstall\ServerInstall\resource\nginx\conf\ssl_params.conf.from.certbot

  #禁用SSL协议，只支持TLS协议。因为SSL协议存在安全性问题
  ssl_protocols TLSv1.2 TLSv1.3;

  #如果您的 OpenSSL 是旧版本，不可用密码将被自动丢弃。总是使用完整的密码套件，让OpenSSL选它所支持的。
  #密码套件的顺序非常重要，因为它决定在优先级算法将被选中。上面的建议重视算法提供完美的向前保密。
  #老版本的 OpenSSL 可能不会返回算法的完整列表。AES-GCM 和一些 ECDHE 相当近，而不是出现在大多数版本的 Ubuntu OpenSSL 附带或 RHEL。
  #优先级逻辑
  #    首先选择 ECDHE + AESGCM 密码。这些都是 TLS 1.2 密码并没有受到广泛支持。这些密码目前没有已知的攻击目标。
  #    PFS 密码套件是首选，ECDHE 第一，然后 DHE。
  #    AES 128 更胜 AES 256。有讨论是否 AES256 额外的安全是值得的成本，结果远不明显。目前，AES128 是首选的，因为它提供了良好的安全，似乎真的是快，更耐时机攻击。
  #    向后兼容的密码套件，AES 优先 3DES。暴力攻击 AES 在 TLS1.1 及以上，减轻和 TLS1.0 中难以实现。向后不兼容的密码套件，3DES 不存在.
  #    RC4 被完全移除. 3DES 用于向后兼容。 

  #强制性的丢弃
  #    aNULL 包含未验证 diffie - hellman 密钥交换，受到中间人这个攻击
  #    eNULL 包含未加密密码(明文)
  #    EXPORT 被美国法律标记为遗留弱密码
  #    RC4 包含了密码，使用废弃ARCFOUR算法
  #    DES 包含了密码，使用弃用数据加密标准
  #    SSLv2 包含所有密码,在旧版本中定义SSL的标准,现在弃用
  #    MD5 包含所有的密码，使用过时的消息摘要5作为散列算法

  #openssl命令：
  #openssl ciphers -V | column -t #查看支持的加密套件

  #推荐的密码套件:
  #ssl_ciphers 'AES128+EECDH:AES128+EDH';

  #推荐的密码套件向后兼容(IE6 / WinXP):
  #ssl_ciphers "ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";

  #参考：
  #如何在NGINX网站服务器中实施SSL完美前向保密技术? http://netsecurity.51cto.com/art/201408/447473.htm
  #ssl_ciphers "EECDH+ECDSA+AESGCM EECDH+aRSA+AESGCM EECDH+ECDSA+SHA384 \
  #EECDH+ECDSA+SHA256 EECDH+aRSA+SHA384 EECDH+aRSA+SHA256 EECDH+aRSA+RC4 \
  #EECDH EDH+aRSA RC4 !aNULL !eNULL !LOW !3DES !MD5 !EXP !PSK !SRP !DSS !MEDIUM";

  #使用命令行 openssl ciphers '{ssl_ciphers定义的字符串}' #可以查看实际的套件与优先顺序
  ssl_ciphers "ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-SHA384:ECDHE-ECDSA-AES128-SHA256:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4";

}
`

==============================
nuster测试结果：
ab -c 100 -n 3000 https://sl266.com/AdminLTE/index3.html
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking sl266.com (be patient)
Completed 300 requests
Completed 600 requests
Completed 900 requests
Completed 1200 requests
Completed 1500 requests
Completed 1800 requests
Completed 2100 requests
Completed 2400 requests
Completed 2700 requests
Completed 3000 requests
Finished 3000 requests

Server Software:        xxh
Server Hostname:        sl266.com
Server Port:            443
SSL/TLS Protocol:       TLSv1.2,ECDHE-ECDSA-AES256-GCM-SHA384,384,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        sl266.com

Document Path:          /AdminLTE/index3.html
Document Length:        43692 bytes

Concurrency Level:      100
Time taken for tests:   60.085 seconds
Complete requests:      3000
Failed requests:        1
   (Connect: 0, Receive: 0, Length: 1, Exceptions: 0)
Non-2xx responses:      1
Total transferred:      132223144 bytes
HTML transferred:       131032418 bytes
Requests per second:    49.93 [#/sec] (mean)
Time per request:       2002.831 [ms] (mean)
Time per request:       20.028 [ms] (mean, across all concurrent requests)
Transfer rate:          2149.03 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      597  969 702.4    697   13199
Processing:     1  892 490.7    756    6980
Waiting:        0  436 299.9    273    4952
Total:       1106 1861 979.8   1475   13200

nginx测试结果：
 ab -c 100 -n 3000 https://sl266.com:444/AdminLTE/index3.html
This is ApacheBench, Version 2.3 <$Revision: 1843412 $>
Copyright 1996 Adam Twiss, Zeus Technology Ltd, http://www.zeustech.net/
Licensed to The Apache Software Foundation, http://www.apache.org/

Benchmarking sl266.com (be patient)
Completed 300 requests
Completed 600 requests
Completed 900 requests
Completed 1200 requests
Completed 1500 requests
Completed 1800 requests
Completed 2100 requests
Completed 2400 requests
Completed 2700 requests
Completed 3000 requests
Finished 3000 requests

Server Software:        xxh
Server Hostname:        sl266.com
Server Port:            444
SSL/TLS Protocol:       TLSv1.2,ECDHE-ECDSA-AES256-GCM-SHA384,384,256
Server Temp Key:        X25519 253 bits
TLS Server Name:        sl266.com

Document Path:          /AdminLTE/index3.html
Document Length:        43692 bytes

Concurrency Level:      100
Time taken for tests:   47.790 seconds
Complete requests:      3000
Failed requests:        2112
   (Connect: 0, Receive: 0, Length: 2112, Exceptions: 0)
Non-2xx responses:      2111
Total transferred:      40538810 bytes
HTML transferred:       39841330 bytes
Requests per second:    62.77 [#/sec] (mean)
Time per request:       1593.005 [ms] (mean)
Time per request:       15.930 [ms] (mean, across all concurrent requests)
Transfer rate:          828.39 [Kbytes/sec] received

Connection Times (ms)
              min  mean[+/-sd] median   max
Connect:      599 1001 649.7    706   10784
Processing:     0  496 429.3    240    3661
Waiting:        0  335 256.2    237    3204
Total:        798 1497 842.0   1187   10784

Percentage of the requests served within a certain time (ms)
  50%   1187
  66%   1560
  75%   1834
  80%   2050
  90%   2565
  95%   3239
  98%   3964
  99%   4521
 100%  10784 (longest request)

【结论】没有必须使用nuster，直接使用nginx就可以。

**Comment by jiangwenyuan** [comment]
Complete requests: 3000
Failed requests: 2112
(Connect: 0, Receive: 0, Length: 2112, Exceptions: 0)
Non-2xx responses: 2111

**Comment by senioi** [comment]
我个人觉得nuster不是一个CDN or ADN 产品,它的定位我一直很迷惑.
而且性能我在以前的nuster版本上进行过测试和在生产环境上运行了几个星期,最后因为各类连接问题和缓存问题最后放弃了.
如果你想使用高性能的LB,但是又想缓存前端部分资源,我觉得haproxy的本体已经完全可以满足需求了,请看这:
https://www.haproxy.com/documentation/aloha/12-5/traffic-management/lb-layer7/caching-small-objects/
如果你想改善体验,考虑下其他支持QUIC产品,比如litespeed ADC

**Comment by jiangwenyuan** [comment]
> 我个人觉得nuster不是一个CDN or ADN 产品,它的定位我一直很迷惑.
> 而且性能我在以前的nuster版本上进行过测试和在生产环境上运行了几个星期,最后因为各类连接问题和缓存问题最后放弃了.
> 如果你想使用高性能的LB,但是又想缓存前端部分资源,我觉得haproxy的本体已经完全可以满足需求了,请看这:
> https://www.haproxy.com/documentation/aloha/12-5/traffic-management/lb-layer7/caching-small-objects/

删除了商业产品
