### ISSUE TITLE
Support 304 answers?

### ISSUE THREAD

**Issue by everyx** [jiangwenyuan/nuster#114]
I found that nuster return `200` forever when request with `If-None-Match` header even if there is nothing change, but nuster should return `304`.

btw: I have already set `ETag` header

> Once a resource is stored in a cache, it could theoretically be served by the cache forever. Caches have finite storage so items are periodically removed from storage. This process is called cache eviction. On the other side, some resources may change on the server so the cache should be updated. As HTTP is a client-server protocol, servers can't contact caches and clients when a resource changes; they have to communicate an expiration time for the resource. Before this expiration time, the resource is fresh; after the expiration time, the resource is stale. Eviction algorithms often privilege fresh resources over stale resources. Note that a stale resource is not evicted or ignored; when the cache receives a request for a stale resource, it forwards this request with a If-None-Match to check if it is in fact still fresh. If so, the server returns a 304 (Not Modified) header without sending the body of the requested resource, saving some bandwidth.

_- from https://developer.mozilla.org/en-US/docs/Web/HTTP/Caching_

Maybe somthing related? - https://github.com/haproxy/haproxy/issues/214

**Comment by jiangwenyuan** [comment]
@everyx 

Check
https://github.com/jiangwenyuan/nuster#last-modified-onoff
https://github.com/jiangwenyuan/nuster#etag-onoff

**Comment by everyx** [comment]
Great, it works, thanks :)
