### ISSUE TITLE
Can we force the first request return stale cache when stale on?

### ISSUE THREAD

**Issue by everyx** [jiangwenyuan/nuster#115]
and nuster send request to the backend server and update the cache at the same time.

btw, does the `purge` request mark the cache `stale`, and not directly deleting it? so nuster can still use the stale cache?

I want to ensure that the cache can be updated, and users will not feel that the server slows down accordingly at the same time.

**Comment by jiangwenyuan** [comment]
> Can we force the first request return stale cache when stale on?

Yes

> and nuster send request to the backend server and update the cache at the same time.

Not yet, it's on the todo list..

> btw, does the purge request mark the cache stale, and not directly deleting it? so nuster can still use the stale cache?

No, purge mark the cache invalid

**Comment by everyx** [comment]
> > Can we force the first request return stale cache when stale on?
> 
> Yes

How to do that? According to the [comment in this issues](https://github.com/jiangwenyuan/nuster/issues/96#issuecomment-676454413), the first request will be always forwarded to the backend and response the return content then.

> 
> > and nuster send request to the backend server and update the cache at the same time.
> 
> Not yet, it's on the todo list..

Great. exciting to wait this come true

> > btw, does the purge request mark the cache stale, and not directly deleting it? so nuster can still use the stale cache?
> 
> No, purge mark the cache invalid

Will cleaner clean up the stale caches immediately? Is there a plan to support mark cache's status to `stale` manually?

**Comment by jiangwenyuan** [comment]
My bad..It's still on the local development branch..I haven't  touched on this for a while:)

> Will cleaner clean up the stale caches immediately?

No

> Is there a plan to support mark cache's status to stale manually?

Not as of now..

**Comment by everyx** [comment]
> My bad..It's still on the local development branch..I haven't touched on this for a while:)

hope it can be comming soon :)

> > Will cleaner clean up the stale caches immediately?
> 
> No

So can you give more details about stale caches cleanup process?

I want that the cache of stale will never be deleted until the memory / disk is about to exceeds the quota and running LRU cleanup then. So I can use cache as much as I can.

**Comment by jiangwenyuan** [comment]
> So can you give more details about stale caches cleanup process?

It is controlled by disk-cleaner, if the file is stale ON or within stale TIME, it will not be deleted.

**Comment by everyx** [comment]
> > So can you give more details about stale caches cleanup process?
> 
> It is controlled by disk-cleaner, if the file is stale ON or within stale TIME, it will not be deleted.

So the stale cache will never be deleted and will only be updated by the new cache?

**Comment by jiangwenyuan** [comment]
It will be deleted if stale TIME is expired
