### ISSUE TITLE
timeout if server directive is missing port

### ISSUE THREAD

**Issue by ronald** [jiangwenyuan/nuster#119]
If you forget to set port in server directive, you get timeouts.
I could not find any hint on this in the nuster output (even with -d). 

What does nuster do while missing the port setting? 
Should this config be rejected as invalid?

Example config:

```
global
    nuster cache on

defaults
    retries 3
    timeout client  30s
    timeout connect 30s
    timeout server  30s
frontend fe
    bind *:8080
    mode http
    default_backend be

backend be
    mode http
#    server s1 10.0.0.3:80
    server s1 10.0.0.3

```

**Comment by jiangwenyuan** [comment]
@ronald 

https://cbonte.github.io/haproxy-dconv/2.0/configuration.html#4.2-server

> [port]    is an optional port specification. If set, all connections will
          be sent to this port. If unset, the same port the client
          connected to will be used.

**Comment by ronald** [comment]
Thanks for clarification. 

Shall we extend the [readme](https://github.com/jiangwenyuan/nuster/blob/master/README.md?plain=1#L1143)?

## How to debug?

Start `nuster` with `-d`.


## What could be the cause of 504 gateway timeout?

Please check your backend settings. Did you specify a port in the server directive? If set, all connections will
be sent to this port. If unset, the same port the client connected to will be used.
```
backend be
    mode http
    server s1 10.0.0.3:80
```

**Comment by jiangwenyuan** [comment]
@ronald Welcome PR!

**Comment by ronald** [comment]
Sorry, didn't update cn/jp.

**Comment by jiangwenyuan** [comment]
Thanks!
