### ISSUE TITLE
作为地图瓦片服务缓存时同名文件名缓存问题(url不一样)

### ISSUE THREAD

**Issue by maxid** [jiangwenyuan/nuster#12]
**Is this a BUG report or FEATURE request?**:
作为地图瓦片服务缓存时同名文件名缓存问题(url不一样)，默认缓存是按文件名缓存，而不是按url缓存？
地图瓦片服务不同的level下，会有文件名相同的情况，那样经过缓存后，在不同的level下，访问文件名相同，但URL是不一样的，只会返回首次缓存的内容！
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- OS (CentOS? Ubuntu?...)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jiangwenyuan** [comment]
@maxid 感谢使用和反馈。能详细说明下吗？比如URL和文件名实例。默认是按照URL缓存的。

**Comment by maxid** [comment]
如下图所示
![image](https://user-images.githubusercontent.com/927429/38763135-deed00b0-3fc7-11e8-88d6-9f6fcdc965a4.png)

**Comment by maxid** [comment]
使用缓存后的效果如下，如果不使用，则正常
![image](https://user-images.githubusercontent.com/927429/38763167-5a2fd98c-3fc8-11e8-912b-7e5b1b819280.png)

**Comment by jiangwenyuan** [comment]
可以在global加入`debug`，查看key，默认情况下key是 `GET.http.localhost:63342.arctile-decode/data/decode/_alllayers/L2/R000004d5/C00000698.ng`

**Comment by jiangwenyuan** [comment]
有没有办法可以在我这边重现？比如提供一个后端app的docker image?

**Comment by maxid** [comment]
好的，我试下，backend看看能否提供吧

**Comment by jiangwenyuan** [comment]
OK，方面的话可以把debug输出的信息提供一下，有私密信息的话邮件发送也可以

**Comment by maxid** [comment]
开启了debug模式，但使用docker logs看不到有相关日志输出

**Comment by jiangwenyuan** [comment]
用的docker啊，现在的image不支持logs。可以这样
` docker run -it -p 8080:8080 -v $HOME/conf:/etc/nuster/nuster.cfg:ro nuster/nuster bash`
然后
`root@30389101a087:/# haproxy -f /etc/nuster/nuster.cfg`

**Comment by jiangwenyuan** [comment]
@maxid Hi，请问这个问题有没有解决呢？这两天会发布下一个版本，如果确定是bug希望可以修复之前再发布
