### ISSUE TITLE
incorrect date header

### ISSUE THREAD

**Issue by ronald** [jiangwenyuan/nuster#122]
## Expected Behavior
response header date should be set to now: 
Date: Fri, 17 Dec 2021 09:00:02 GMT

## Current Behavior
date: Thu, 16 Dec 2021 14:33:29 GMT
I assume this is time of caching.

## Steps to Reproduce
```
   global
        nuster cache on data-size 200m dir /nuster-cache
        master-worker # since v3

    defaults
        mode http

    frontend fe
        bind *:8080
        default_backend be1

    backend be1
        nuster cache on
        nuster rule all                  key method.host.uri disk on   ttl 30d
        server s1 backend-server:80
```

I am not sure that the problem is caused by nuster. Is that possible?

**Comment by jiangwenyuan** [comment]
@ronald You can put this line to frontend:

    http-response set-header Date %[date(),http_date]

**Comment by ronald** [comment]
Thanks a lot.
