### ISSUE TITLE
Have a plan support comparing "Last-Modified" with "If-Modified-Since"?

### ISSUE THREAD

**Issue by zabio3** [jiangwenyuan/nuster#15]
I set response header with "Last-Modified" in an application.

Therefore, when the application's content expires on client browser, it inquires the application with request header "If-Modified-Since".

I want to use nuster as cache server, but I don't know to compare "Last-Modified" with "If-Modified-Since" by using nuster.

Is it possible to do the above comparison?

**Comment by zabio3** [comment]
Thank you for your immediate reply !

It is included in todo : )
I would like to send pr if possible.

**Comment by jiangwenyuan** [comment]
Finally added.
7e9038a0c11604b3f6b731702cd6e821d41d4a17

**Comment by zabio3** [comment]
Thank you for adding the feature :+1:
