### ISSUE TITLE
Can "nuster" use disk as cache area?

### ISSUE THREAD

**Issue by zabio3** [jiangwenyuan/nuster#16]
If "nuster" consume fully the cache area of memory, I make it to save the cache on disk. 
(Priority order : memory cache area -> disk cache area)

**Comment by jiangwenyuan** [comment]
No, currently nuster only use memory as storage, I'm working on disk persistence right now, also syncing between nodes is also planned.

**Comment by zabio3** [comment]
Thank you for your immediate reply : )

I expect that the function will be upgraded.

**Comment by shannonantony** [comment]
syncing cache data among the nodes will be really great. do you have any timeline on that. I love nuster

thanks

**Comment by Ara4Sh** [comment]
@jiangwenyuan Im also interested to cache the contents in disk and replication , thank you alot

**Comment by dampersand** [comment]
Commenting to both express interest in this enhancement and thank @jiangwenyuan for the incredible work on this project as it stands!

**Comment by jiangwenyuan** [comment]
Hi, thanks for the feedback, I've almost finished disk persistence, with several issues to fix, hopefully, I could push to master this week.

**Comment by jiangwenyuan** [comment]
Released

**Comment by Ara4Sh** [comment]
@jiangwenyuan You did an amazing job, Im going to test it :+1:
