### ISSUE TITLE
Display cache stats by host

### ISSUE THREAD

**Issue by zabio3** [jiangwenyuan/nuster#17]
I want to get statistics data by host.
However, only all statistics data can be acquired now.

Have a plan support to do the above matters?

**Comment by jiangwenyuan** [comment]
No plans right now. I could look into it after several big features I'm working on. anyway PR is always welcomed:)

**Comment by zabio3** [comment]
Thank you for your immediate reply !

I would like to send pr if possible.

**Comment by igorescobar** [comment]
@zabio3 What I'm going to "solve" this is by making the access log using a JSON format. Then, I'm using CloudWatch Insights to query and aggregate the data for me but it would work with any other service like Datadog, Logz or something like Kibana + Logstash.

On my case, I don't care much about the host itself this can give me a good overview of in a period of time how many requests went trough the cache:

![Screenshot 2020-05-23 at 16 03 29](https://user-images.githubusercontent.com/24032/82733877-f395b880-9d0e-11ea-84b6-5d073a4b3def.png)

This is the query:
```sql
parse @message '"server":"*"' as server
  | parse @message '"uri":"*"' as path
  | parse @message '"status_code":*,' as status_code
  | filter path not like /health_check/
  | filter status_code = 200
  | stats count(*) as hits by server
  | sort by hits desc
```

Cheers!

**Comment by zabio3** [comment]
Thank you for including the query. By using the access log that you have proposed and totaling it, you can see the statistical information for each path, so I would like to solve this issue itself. 
Cheers!
