### ISSUE TITLE
Purging cache

### ISSUE THREAD

**Issue by jbergstroem** [jiangwenyuan/nuster#2]
nuster should support purging via `HTTP PURGE` to the same endpoint (with ACL; usually just matching over addr/netmask). Bonus points for globbing (`*.jpg`).

**Comment by frank0826** [comment]
How do you count the cache hit rate of nuster ？

**Comment by jiangwenyuan** [comment]
@jbergstroem @frank0826 These features will be added in next version(v1.7.9.3), including purging cache(by key, by name, by tag...), enable/disable caching on the fly, cache stats(hit rate, mem usage, etc).

**Comment by jiangwenyuan** [comment]
@jbergstroem @frank0826 Purging is added. There are various way to purge. Please see https://github.com/jiangwenyuan/nuster#purge-cache
Please have a try.
stats will be added in next release.

**Comment by jiangwenyuan** [comment]
@frank0826 cache stats has been added. Please take a look https://github.com/jiangwenyuan/nuster#cache-stats
