### ISSUE TITLE
Is H2O HTTP Server faster than Nginx?

### ISSUE THREAD

**Issue by proyb6** [jiangwenyuan/nuster#25]
Saw a comment link to https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark%3A-nuster-vs-nginx-vs-varnish-vs-squid

In additional, I've been running H2O HTTP Server if you are curious how its fare and it's faster than Nginx on my VPS with maximum tuning, how does it compare to nuster in your beef hardware? I'm curious. TechEmpower Benchmark seem to shown it's blazing fast.

https://h2o.examp1e.net/

I can provide you the h2o.conf file if you need it.

**Comment by jiangwenyuan** [comment]
Hi, 

I benchmarked the static file performance of h2o and nginx(https://h2o.examp1e.net/benchmarks.html, latest version at that time), as h2o does not have cache ability,  but didn't get the same result h2o claimed. Maybe I did something wrong, I'm happy to test if you can provide h2o.conf. 

BTW, here's a http/2 cache benchmark of nuster vs nginx: https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-HTTP-2-performance-benchmark%3A-nuster-vs-nginx

**Comment by proyb6** [comment]
Yup, H2O will need MRuby-Hiredis (https://github.com/Asmod4n/mruby-hiredis) using unix socket or MRuby-localmemcache (https://github.com/matsumotory/mruby-localmemcache)

Both can ```git clone``` into the H2O deps folder and cmake without additional configuration provided either redis or memcache are running respectively.

Although, I haven't started to test localmemcache yet, I can share redis version.

```
"example.com:8080":
  listen:
    port: 8080
  paths:
    "/redis":
      mruby.handler: |
        hiredis = Hiredis.new("/var/run/redis/redis.sock", -1)
        Proc.new do |env|
# Retrieve value
            cached = hiredis["hello"]
# Store value
            hiredis["hello"] = "Hello World"
          end
          [200, {'content-type' => 'text/plain'}, [cached]]
        end
```


Great thanks for your time on http/2 cache benchmark!

**Comment by jiangwenyuan** [comment]
Thanks, let me do the test and get back here once done.

Meanwhile, great to see your test of h2o vs nuster vs nginx, you can use the config file here:
https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-HTTP-2-performance-benchmark%3A-nuster-vs-nginx :)

**Comment by proyb6** [comment]
I'm also unsure if those sysctl tweaks recommend could boost network performance or may have a negative impact for low-memory VPS?

sysctl.conf 
```
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
```

For your info if you like to test:
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/C/h2o
https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Ruby/h2o_mruby


How about participate in TechEmpower benchmark? We will get a better idea where it stands.

**Comment by jiangwenyuan** [comment]
I've tested using both master branch of h2o and nuster

nuster.conf: 

https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-HTTP-2-performance-benchmark%3A-nuster-vs-nginx

h2o.conf:

```
max-connections: 1000000
error-log: /tmp/h2o.err

hosts:
  "example.com":
    listen:
      port: 8080
    paths:
      "/redis":
        mruby.handler: |
          hiredis = Hiredis.new("/var/run/redis/redis.sock", -1)
          headers = {}
          Proc.new do |env|
            cached = hiredis["foo"]
            if cached.nil? then
              env.each do |key, value|
                if /^HTT_/.match(key)
                  headers[$'] = value
                end
              end
              cached = http_request(
                "http://10.146.0.4/hello",
                method: env["REQUEST_METHOD"],
                headers: headers,
                body: env["rack.input"],
              ).join[2].join
              hiredis["foo"] = cached
            end
            [200, {'content-type' => 'application/octet-stream', 'Last-Modified' =>'Sun, 12 Aug 2018 11:10:23 GMT', 'ETag' => "5b", 'Accept-Ranges' => 'bytes' }, [cached]]
          end
```

I added some header to make response the same size:

```
# curl -is http://10.146.0.3:8081/hello
HTTP/1.1 200 OK
Server: nginx/1.10.3
Date: Mon, 13 Aug 2018 00:06:29 GMT
Content-Type: application/octet-stream
Content-Length: 11
Last-Modified: Sun, 12 Aug 2018 11:10:23 GMT
ETag: "5b70159f-b"
Accept-Ranges: bytes
Connectio1: keep-aliv1

helloworld
# curl -is http://10.146.0.3:8081/hello | wc
     11      30     261
# curl -is http://10.146.0.3:8080/redis
HTTP/1.1 200 OK
Connection: keep-alive
Content-Length: 11
Server: h2o/2.3.0-DEV@821bb31f
content-type: application/octet-stream
last-modified: Sun, 12 Aug 2018 11:10:23 GMT
etag: 5b
accept-ranges: bytes
date: Mon, 13 Aug 2018 00:06:44 GMT

helloworld
# curl -is http://10.146.0.3:8080/redis | wc
     11      30     261
```

and here's the result:

```
### h2o
#  wrk -c 1000 -t 1000 -d 30 http://10.146.0.3:8080/redis
Running 30s test @ http://10.146.0.3:8080/redis
  1000 threads and 1000 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    12.40ms    5.53ms  86.55ms   95.17%
    Req/Sec    83.52     19.08   747.00     80.31%
  2516291 requests in 30.11s, 626.30MB read
  Non-2xx or 3xx responses: 314
Requests/sec:  83582.60
Transfer/sec:     20.80MB

### nuster
#  wrk -c 1000 -t 1000 -d 30 http://10.146.0.3:8081/hello
Running 30s test @ http://10.146.0.3:8081/hello
  1000 threads and 1000 connections
^B0  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     2.80ms    1.04ms 103.52ms   89.36%
    Req/Sec   363.58     66.73     3.28k    86.14%
  10952325 requests in 30.11s, 2.66GB read
Requests/sec: 363798.11
Transfer/sec:     90.55MB

```

so nuster : 363798, and h2o: 83582, with errors

As the TechEmpower you mentioned, nuster is not suited, as it's a cache server not a http server, although you can use lua with nuster to implement a http server.

**Comment by proyb6** [comment]
I will be more curious if combining H2O and nuster will be possible? I was thinking about the possibility like LiteSpeed Cache for Wordpress is design to work with LiteSpeed engine.

If H2O and nuster are very well complement to each other, I will be keen to experiment on community sites.

**Comment by jiangwenyuan** [comment]
yeah, it's possible. for example, put nuster in front of h2o, nuster will accept request from user and forward to h2o

nuster.conf

```
frontend web
    bind *:80
    mode http
    default_backend h2o

backend h2o
    balance     roundrobin
    mode http

    nuster cache on

    acl static path_beg -i /static/ /images/ /css/
    nuster rule static_files ttl 0 if static

    server h2o_server1 10.0.0.10:8080
    server h2o_server2 10.0.0.11:8080
```

**Comment by proyb6** [comment]
Nuster can run as HTTP/2 and rename/redirect the request URL if I need to return different files?

Return the user request instead of index.html it return indexhttps.html

**Comment by proyb6** [comment]
I seem to see your config  is Server: nginx/1.10.3?

**Comment by jiangwenyuan** [comment]
> Nuster can run as HTTP/2 and rename/redirect the request URL if I need to return different files?
yeah, no problem

> How does it work with HTTP2 Push?
Not yet, have a plan of it

> Return the user request instead of index.html it return indexhttps.html
no problem

> I seem to see your config is Server: nginx/1.10.3?

yeah, the origin server is nginx, nuster is in front of nginx, nuster will forward first request to nginx and cache the response, then serve the rest request by itself.

**Comment by proyb6** [comment]
I get the idea, so the H2O in this test is on 12 cores?

Lastly, how it fare on 1 core with H2Load without the Hiredis, just  since I'm curious how it stack up against Nginx

https://github.com/TechEmpower/FrameworkBenchmarks/tree/master/frameworks/Ruby/h2o_mruby

**Comment by jiangwenyuan** [comment]
Yeah, it's on 12 cores. 

That would be interesting:)
