### ISSUE TITLE
Data size 4K, 8K, 16K and 32K

### ISSUE THREAD

**Issue by proyb6** [jiangwenyuan/nuster#26]
Most of the sites will have a large files size as mine HTML is nearly 16KB (compressed)

Should Nuster includes more data size?

**Comment by jiangwenyuan** [comment]
You mean in the test? 

nuster can cache any size of response.

**Comment by proyb6** [comment]
I mean I like to see more results in the existing benchmark

**Comment by jiangwenyuan** [comment]
I'd like to that too, my test network is 1G, if i test 1kb file with 1000 connections, the whole bandwidth is used. so the results do not make much difference

**Comment by proyb6** [comment]
I see, I’m thinking if a VPS has more network bandwidth
