### ISSUE TITLE
update cache record ttl

### ISSUE THREAD

**Issue by Dexus77** [jiangwenyuan/nuster#29]
**Is this a BUG report or FEATURE request?**:
FEATURE request

I'll support zabio3.
Last-Modified support and cache search would be nice.

I'd like to be able to extend TTL cache records at the level of the rules.

Idea in what

Cache private user page for a user session for example for 5 minutes, if the user repeatedly accesses the page within 5 minutes, extend its record TTL for another 5 minutes.

Perhaps this can already be somehow realized, but I did not have the patience or brains to understand how :)

**Comment by jiangwenyuan** [comment]
Added: https://github.com/jiangwenyuan/nuster#extend-extend
