### ISSUE TITLE
Health Check

### ISSUE THREAD

**Issue by fmoessle** [jiangwenyuan/nuster#33]
How can I perform a health check when using nuster as a http cache proxy? I only want to check the health of the proxy and not the server I want to cache.

**Comment by jiangwenyuan** [comment]
Hi, you can use [monitor-uri](https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#4-monitor-uri) 

```
frontend www
    mode http
    monitor-uri /haproxy_test
```

Or you can use [nuster uri](https://github.com/jiangwenyuan/nuster#uri-cache-only)

`nuster cache on uri /_my/_unique/_/_cache/_uri`

So you can use these urls for health check

**Comment by fmoessle** [comment]
Thank you!
