### ISSUE TITLE
WebSocket or Messagepack for reverse proxy to microservices

### ISSUE THREAD

**Issue by proyb6** [jiangwenyuan/nuster#34]
I'm thinking on the idea if Nuster could communicate with backend microservices using WebSocket protocol or messagepack instead of HTTP for low latency and less overhead?

**Comment by jiangwenyuan** [comment]
Hi, is this what you what?

https://www.haproxy.com/blog/websockets-load-balancing-with-haproxy/

**Comment by proyb6** [comment]
How well does it work if we upgrade to websocket for clients and web browser or any concern with security?

**Comment by jiangwenyuan** [comment]
You should have some tests and benchmarks:)
