### ISSUE TITLE
ACL dont work anymore after upgrade to nuster v2.0.5.18

### ISSUE THREAD

**Issue by rodkevchen** [jiangwenyuan/nuster#36]
After I upgraded Nuster to v2.0.5.18 one of my ACL dont work anymore.

I used following ACL Command to cache all content with a specific Content-Type in my case "image/jpeg" and "image/png". 

```
acl CacheContentTypeRule  res.hdr(Content-Type) -f /etc/nuster/file_pattern_for_cache.txt
nuster rule resCache ttl 3600 if CacheContentTypeRule
```

```
#cat /etc/nuster/file_pattern_for_cache.txt 
image/jpeg
image/png
```

But after the upgrade it seems the ACL dont work anymore. The othere ACLs are still working correctly.

**Environment**:
- OS (Ubuntu 18.04.1)
- Kernel (4.15.0-43-generic):

I saw there was some "Fix incorrect acl check" fixes in the version. So is this a bug or maybe a missconfiguration in the ACL on my site?

Thx,

**Comment by jiangwenyuan** [comment]
Thanks for the reporting, this indeed is a bug introduced by that fix.

**Comment by jiangwenyuan** [comment]
fixed, thanks
