### ISSUE TITLE
Are versions consistent with HAProxy?

### ISSUE THREAD

**Issue by amit777** [jiangwenyuan/nuster#37]
Is the versioning strategy of this project to maintain parity with HAProxy? I guess I'm trying to understand if this is truly just using HAProxy's core for each version then apply Nuster features as patches on top of it.. Or is it a completely divergent fork?

**Comment by jiangwenyuan** [comment]
Hi, nuster is built on top of HAProxy, thus 100% compatible with it.

check https://github.com/jiangwenyuan/nuster/blob/master/Download.md#legacy-versions
