### ISSUE TITLE
有考虑缓存http内容到硬盘吗？

### ISSUE THREAD

**Issue by 9527code** [jiangwenyuan/nuster#38]
有考虑缓存http内容到硬盘吗？全是内存应该不够用.能缓存到SSD就好了

**Comment by jiangwenyuan** [comment]
@9527code 刚刚开始着手开发保存到硬盘功能

**Comment by 9527code** [comment]
可考虑结合 https://github.com/chrislusf/seaweedfs
感觉可行

**Comment by jiangwenyuan** [comment]
谢谢
