### ISSUE TITLE
缓存规则是否支持正则？

### ISSUE THREAD

**Issue by 9527code** [jiangwenyuan/nuster#39]
`^.+\.(jpg|jpeg|gif|bmp|png|ico)$`
缓存所有图片怎么操作？

**Comment by 9527code** [comment]
尝试使用
acl html path -m reg -i ^.+\.html$
acl html path_reg -i ^.+\.html$
acl html path_reg -i .+\.html


都没用
nuster rule img ttl 1d if html

**Comment by jiangwenyuan** [comment]
@9527code 已经close，是解决了吗？

支持正则，具体可以看 https://cbonte.github.io/haproxy-dconv/1.8/configuration.html#7

缓存所有图片可以用

`acl images path_end -i .jpg .jpeg .gif .bmp .png .ico` 

如果用path_reg的话，可以用类似

`nuster rule images if { path_reg \.(png|jpg|gif)$ }`
