### ISSUE TITLE
为了方便调试有没有办法返回一个Header表明已经命中或者没有缓存？

### ISSUE THREAD

**Issue by 9527code** [jiangwenyuan/nuster#41]
例如返回一个头
N-Cache: HIT
或
N-Cache: MISS

**Comment by jiangwenyuan** [comment]
目前没有这个功能，可以很方便添加。

**Comment by jiangwenyuan** [comment]
添加了 `nuster.cache.hit` 变量， 可以像如下使用

    http-response set-header xcache hit if { nuster.cache.hit }
