### ISSUE TITLE
Segmentation fault on rule

### ISSUE THREAD

**Issue by solonik1** [jiangwenyuan/nuster#43]
**What happened**:
[CACHE] [RES] Checking if rule pass: [ALERT] 136/154924 (1) : Current worker #1 (6) exited with code 139 (Segmentation fault)

**How to reproduce it (as minimally and precisely as possible)**:
nuster rule test ttl 60 if { urlp(filter[test]) -m found }

**Description**:
If i try to cache with this rule "urlp(filter[test]) -m found" nuster got segmentation fault.

Rules with { path_beg /* } works fine.

Thx for help

**Comment by jiangwenyuan** [comment]
@solonik1 Are you using v2.1.2.19? I confirmed that this bug on v2.1.2.19. It works well on stable release  v2.0.10.18. Can you test on  v2.0.10.18?

v2.1.2.19 is a development release and has not been fully tested.

**Comment by solonik1** [comment]
Im on 2.1.2.19.
You're right. It works with the version v2.0.10.18.
This issue can be closed.

Thanks for your answer.

**Comment by jiangwenyuan** [comment]
@solonik1 Fixed
