### ISSUE TITLE
是否可以用于缓存视频切片

### ISSUE THREAD

**Issue by lystormenvoy** [jiangwenyuan/nuster#44]
按照http cache的配置文件配置了
希望用来缓存hls点播，似乎不成功
后端是使用一个nginx做web服务器，播放hls点播文件。使用nuster做代理及缓存，似乎并没有缓存，而是直接回源了。

**Comment by jiangwenyuan** [comment]
@lystormenvoy 请问用的是哪个版本？2.1.2.19版本是测试版，有bug。稳定版是2.0.10.18。

没试过hls点播，切片，如果有可复现的环境(比如dockerfile之类)，很乐意调试。

**Comment by lystormenvoy** [comment]
`00000008:fe.clireq[0004:0005]: GET /hls/ts/out052.ts HTTP/1.1
00000008:fe.clihdr[0004:0005]: Host: 192.168.8.74:8080
00000008:fe.clihdr[0004:0005]: Connection: keep-alive
00000008:fe.clihdr[0004:0005]: Origin: http://192.168.13.251:6080
00000008:fe.clihdr[0004:0005]: User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.100 Safari/537.36
00000008:fe.clihdr[0004:0005]: Accept: */*
00000008:fe.clihdr[0004:0005]: Referer: http://192.168.13.251:6080/
00000008:fe.clihdr[0004:0005]: Accept-Encoding: gzip, deflate
00000008:fe.clihdr[0004:0005]: Accept-Language: zh-CN,zh;q=0.9,en;q=0.8
[CACHE] Checking rule: all
[CACHE] Calculate key: method.scheme.host.uri.
[CACHE] Got key: GETHTTP192.168.8.74:8080/hls/ts/out052.ts 
[CACHE] Checking key existence: NOT EXIST
[CACHE] [REQ] Checking if rule pass: PASS
00000008:be.srvrep[0004:0005]: HTTP/1.1 200 OK
00000008:be.srvhdr[0004:0005]: Server: nginx/1.17.1
00000008:be.srvhdr[0004:0005]: Date: Tue, 02 Jul 2019 03:04:56 GMT
00000008:be.srvhdr[0004:0005]: Content-Type: video/mp2t
00000008:be.srvhdr[0004:0005]: Content-Length: 287076
00000008:be.srvhdr[0004:0005]: Last-Modified: Tue, 11 Jun 2019 07:51:58 GMT
00000008:be.srvhdr[0004:0005]: Connection: keep-alive
00000008:be.srvhdr[0004:0005]: ETag: "5cff5d9e-46164"
00000008:be.srvhdr[0004:0005]: Expires: Fri, 12 Jul 2019 03:04:56 GMT
00000008:be.srvhdr[0004:0005]: Cache-Control: max-age=864000
00000008:be.srvhdr[0004:0005]: Access-Control-Allow-Origin: *
00000008:be.srvhdr[0004:0005]: Access-Control-Allow-Credentials: true
00000008:be.srvhdr[0004:0005]: Cache-Control: public
00000008:be.srvhdr[0004:0005]: Accept-Ranges: bytes
[CACHE] [RES] Checking status code: PASS
[CACHE] To create
`

做了一下测试，To create不是表示会建立这个缓存吗，为什么我后面再访问的时候还是NOT EXIST

**Comment by jiangwenyuan** [comment]
@lystormenvoy 什么版本？2.1.2.19有这个bug

**Comment by lystormenvoy** [comment]
> @lystormenvoy 什么版本？2.1.2.19有这个bug

2.0.10.18

很迷啊，有时可以hit，有时不可以，大部分不可以

**Comment by jiangwenyuan** [comment]
分配的内存是多少？这个文件超过了吗

**Comment by lystormenvoy** [comment]
> 分配的内存是多少？这个文件超过了吗

200m，文件是240MB，这样起码大部分的切片都能缓存吧，况且我视频只看到前一半。

另外问一下，此工具的缓存只使用内存吗？不用硬盘？

**Comment by jiangwenyuan** [comment]
文件超过了分配的内存就不会缓存。
目前的版本只用内存，支持硬盘的目前正在测试，应该过段时间可以发布。

**Comment by lystormenvoy** [comment]
> 文件超过了分配的内存就不会缓存。
> 目前的版本只用内存，支持硬盘的目前正在测试，应该过段时间可以发布。

如果只支持内存就不适合缓存视频了。
一般是内存存高热度的内容，硬盘存相对低热度的吧。trafficserver好像就是这样

**Comment by jiangwenyuan** [comment]
是的，最初就是想短暂缓存动态请求。

**Comment by lystormenvoy** [comment]
> 是的，最初就是想短暂缓存动态请求。如果方便，可以帮忙测试下支持硬盘的版本:)

大概什么时候会有呢

**Comment by jiangwenyuan** [comment]
还有几个问题尚未修复，争取下周先push上来

**Comment by jiangwenyuan** [comment]
添加硬盘持久化功能
