### ISSUE TITLE
Disk persistence modes do not release file handles

### ISSUE THREAD

**Issue by zoltanbalog79** [jiangwenyuan/nuster#49]
Hi,

I would report a major bug of the "disk only" and "disk sync" modes. Potentially the "disk async" mode also suffers from it but that mode was unstable for me so I would not report that.

The issue is that the proxy does not release the opened file handles and this way after a time it eats up all the resources of the host and stops working. The proxy not just loses a file handle when the cache file is created but seems every request which hits the cached file can cause a lost handle.

My haproxy.conf relevant parts:

global
    log         127.0.0.1:601 local0 debug
    user        root
    group       root
    maxconn       200000
    ulimit-n      800000
    stats maxconn 10
    stats socket /var/run/haproxy.sock mode 666 level admin
    nuster nosql off
    nuster cache on data-size 1G dict-size 1G disk-cleaner 10 dict-cleaner 10 data-cleaner 10 dir /tmp/nuster_cache uri /_nuster_stats
    master-worker

defaults
    log     global
    mode    http
    option  httplog
    option  forwardfor
    option  dontlognull
    timeout connect 30s
    timeout client  1m
    timeout server  1m
    timeout check   1m
    timeout tunnel  1m
    timeout queue   1m

frontend http_frontend
    bind *:80
    mode http
    option http-server-close
    reqadd X-Forwarded-Proto:\ http
    default_backend store_http

    http-request set-var(txn.path) path
    http-request set-var(txn.request_method) method

backend store_http
    mode http
    option httpclose
    option forwardfor
    balance leastconn

    acl nuster_getfile var(txn.path) -m beg /getfile/
    acl nuster_is_get var(txn.request_method) -m str GET
    nuster cache
    nuster rule getfile key method.path disk only ttl 2m if nuster_getfile nuster_is_get

How I tested:
I uploaded 100 files and downloaded 4 times all the files.

Before the test on the host there were allocated handles around 2700:
[root@host ~]# sysctl fs.file-nr
fs.file-nr = 2736	0	4875015

After the test run I waited some minutes till all the cached files were already deleted when I checked the allocated handles which was about 400 times more than before:
[root@host ~]# sysctl fs.file-nr
fs.file-nr = 3072	0	4875015

With 'lsof' I see such lines:
haproxy   16321       root   12r      REG              0,119  5851055  906042563 /tmp/nuster_cache/6/65/657faf93738efb1a/469281041867902-16d38a70ec2 (deleted)
haproxy   16321       root   13r      REG              0,119  1317431 2785096705 /tmp/nuster_cache/0/04/0411a0fea8723f15/41180aa80720705-16d38a6fad7 (deleted)
haproxy   16321       root   14r      REG              0,119  3507205 2080421347 /tmp/nuster_cache/c/c9/c9af37ca1d6baa2e/89892140092b8028-16d38a709b6 (deleted)

Counting them:
[root@host ~]# lsof | grep nuster_cache | wc -l
400

So seems if there is a request on a cached file than there will be a lost file handle for every request. If I pick up a hash from the lsof log than I can see:
[root@host ~]# lsof | grep 57e7f3f2d52cc982    
haproxy   16321       root  105r      REG              0,119  6213323 2415968515 /tmp/nuster_cache/5/57/57e7f3f2d52cc982/42c52052d50c4082-16d38a70b45 (deleted)
haproxy   16321       root  155r      REG              0,119  6213323 2415968515 /tmp/nuster_cache/5/57/57e7f3f2d52cc982/42c52052d50c4082-16d38a70b45 (deleted)
haproxy   16321       root  159w      REG              0,119  6213323 2415968515 /tmp/nuster_cache/5/57/57e7f3f2d52cc982/42c52052d50c4082-16d38a70b45 (deleted)
haproxy   16321       root  422r      REG              0,119  6213323 2415968515 /tmp/nuster_cache/5/57/57e7f3f2d52cc982/42c52052d50c4082-16d38a70b45 (deleted)

If I disable the rule "getfile" with the following command than there is no more lost file handle generated anymore:
curl -X POST -H "name: getfile" -H "state: disable" localhost/_nuster_stats
If I kill the haproxy process than all the allocated handles are freed up.
If I use nuster in "disk off" mode than I don't see any lost handle.

Environment:
- OS Ubuntu
- Linux host 3.10.0-862.3.3.el7.x86_64 #1 SMP Fri Jun 15 04:15:27 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I hope the above information is enough to identify the root cause and fix the issue because seems the disk persistence modes currently cannot be used for long term without periodically restarting the proxy service.

**Comment by zoltanbalog79** [comment]
I forgot to include the haproxy build details:
[root@host ~]# haproxy -vv
nuster version 3.0.0.19
Copyright (C) 2017-present, Jiang Wenyuan, <koubunen AT gmail DOT com >

HA-Proxy version 1.9.9 2019/07/23 - https://haproxy.org/
Build options :
  TARGET  = linux2628
  CPU     = generic
  CC      = gcc
  CFLAGS  = -O2 -g -fno-strict-aliasing -Wdeclaration-after-statement -fwrapv -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-old-style-declaration -Wno-ignored-qualifiers -Wno-clobbered -Wno-missing-field-initializers -Wtype-limits
  OPTIONS = USE_ZLIB=1 USE_REGPARM=1 USE_OPENSSL=1 USE_LUA=1 USE_PCRE=1

Default settings :
  maxconn = 2000, bufsize = 16384, maxrewrite = 1024, maxpollevents = 200

Built with OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
Running on OpenSSL version : OpenSSL 1.0.2g  1 Mar 2016
OpenSSL library supports TLS extensions : yes
OpenSSL library supports SNI : yes
OpenSSL library supports : TLSv1.0 TLSv1.1 TLSv1.2
Built with Lua version : Lua 5.3.1
Built with transparent proxy support using: IP_TRANSPARENT IPV6_TRANSPARENT IP_FREEBIND
Built with zlib version : 1.2.8
Running on zlib version : 1.2.8
Compression algorithms supported : identity("identity"), deflate("deflate"), raw-deflate("deflate"), gzip("gzip")
Built with PCRE version : 8.38 2015-11-23
Running on PCRE version : 8.38 2015-11-23
PCRE library supports JIT : no (USE_PCRE_JIT not set)
Encrypted password support via crypt(3): yes
Built with multi-threading support.

Available polling systems :
      epoll : pref=300,  test result OK
       poll : pref=200,  test result OK
     select : pref=150,  test result OK
Total: 3 (3 usable), will use epoll.

Available multiplexer protocols :
(protocols marked as <default> cannot be specified using 'proto' keyword)
              h2 : mode=HTX        side=FE|BE
              h2 : mode=HTTP       side=FE
       <default> : mode=HTX        side=FE|BE
       <default> : mode=TCP|HTTP   side=FE|BE

Available filters :
	[SPOE] spoe
	[COMP] compression
	[CACHE] cache
	[TRACE] trace

**Comment by zoltanbalog79** [comment]
Hi,

I tried to debug the issue and found that somehow in the 'nst_cache_disk_engine_handler' the state machine never goes to state NST_PERSIST_APPLET_DONE. This way the engine.c lines #149 - 151 are never executed which are for closing the file handle. At the moment I don't understand exactly how the disk applet should work but hope that it helps you to figure out the real root cause and fix the issue.

**Comment by zoltanbalog79** [comment]
I have a draft pull request to highlight where are the file handle problems in the code. I don't want to merge it as is to master because the updated code is really just a quick and dirty solution. I just hope that it really helps your work to investigate the issues and fix them permanently.

I continue the investigation of the project because the disk persistent mode is very promising!

**Comment by jiangwenyuan** [comment]
Hi, thank you so much.

It helps a lot.

**Comment by jiangwenyuan** [comment]
@zoltanbalog79 could you please check https://github.com/jiangwenyuan/nuster/tree/fixes/49 ? 
thanks

**Comment by zoltanbalog79** [comment]
@jiangwenyuan Thanks the fix, it is working fine.

**Comment by jiangwenyuan** [comment]
Thanks, pushed to master.

BTW, any issues encountered in "disk async" mode?
