### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [jiangwenyuan/nuster#5]
I would like to point out that identifiers like “[`_PROTO_PATTERN_H`](https://github.com/jiangwenyuan/nuster/blob/fb8248c3ddc39b7e15ce3f5e354f45ffc38c03c1/include/proto/pattern.h#L22 "Update candidate")” and “[`_TYPES_CACHE_H`](https://github.com/jiangwenyuan/nuster/blob/e3fcacdeb3aae05416fda5578cc88534593a80c6/include/types/cache.h#L22 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/c/DCL37-C.+Do+not+declare+or+define+a+reserved+identifier#DCL37-C.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers which are reserved for the compiler implementation.") to the expected naming convention of the C language standard.
Would you like to adjust your selection for unique names?

**Comment by jiangwenyuan** [comment]
Thanks for pointing this out, I completely agree. I'd like to eventually fix this one in order to avoid conflict with HAProxy. It will take some time though.
Thanks again for commenting!

**Comment by elfring** [comment]
How are the chances to [fix affected implementation details](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?") also for [the software “HAProxy”](https://www.haproxy.org/ "Load balancer")?

**Comment by jiangwenyuan** [comment]
It's totally up to them, maybe better to fire an issue.
