### ISSUE TITLE
使用缓存时，能否过滤缓存文件的set-cookies响应头？

### ISSUE THREAD

**Issue by CantonBolo** [jiangwenyuan/nuster#52]
**Is this a BUG report or FEATURE request?**:
如果缓存文件带有set-cookies，其他用户命中缓存文件后有可能产生会话混乱。

**Comment by jiangwenyuan** [comment]
是要把响应里的set-cookies删了吗？

```
http-response del-header set-cookies
```

**Comment by CantonBolo** [comment]
在backend里加上了
'''ini
acl static_content path_end -i .jpg .png .gif .css .js .txt .jpeg .gif .txt .pdf .zip .7z .gz .tar .rar .ico .doc .docx .xls .xlsx .ppt .pptx .exe .pdf .mp4 .mp3 .wav
http-response del-header set-cookies if static_content
```
测试配置文件时提示`acl 'static_content' will never match because it only involves keywords that are incompatible with 'backend http-response header rule'`

**Comment by jiangwenyuan** [comment]
path的话只有request阶段才有效，如果需要在response阶段使用的话，需要将path存起来

```
http-request set-var(txn.path) path
acl static_content var(txn.path) -m end -i .jpg .png .gif .css .js .txt .jpeg .gif .txt .pdf .zip .7z .gz .tar .rar .ico .doc .docx .xls .xlsx .ppt .pptx .exe .pdf .mp4 .mp3 .wav
http-response del-header set-cookies if static_content
```

**Comment by CantonBolo** [comment]
搞定了，谢谢
