### ISSUE TITLE
Routing multiple domains using HTTPS loadbalancer

### ISSUE THREAD

**Issue by enesgur** [jiangwenyuan/nuster#58]
I want to use nuster instead of nginx server. I have a question for to do this.

How can i loadbalancing multiple https domain? 
Example:
https://abc.com => 10.0.0.30
https://xyz.com => 10.0.0.35
https://foo.com => 10.0.0.40

**Comment by packeteer** [comment]
Nuster is based on Haproxy, so their docs should cover this ie. https://www.haproxy.com/blog/haproxy-ssl-termination/

**Comment by jiangwenyuan** [comment]
Thanks @packeteer.

@enesgur Here's some example:

Put certs of abc/xyz/foo into /etc/ssl

```
frontend web
  mode http
  bind *:443 ssl crt /etc/ssl/

  acl site_abc hdr_end(host) -i abc.com
  acl site_xyz hdr_end(host) -i xyz.com 
  acl site_foo hdr_end(host) -i foo.com

  use_backend abc if site_abc
  use_backend xyz if site_xyz 
  use_backend foo if site_foo

backend abc
  mode http
  nuster cache on
   nuster rule all
   server s1 10.0.0.30:80

```

**Comment by enesgur** [comment]
Thank you all.
