### ISSUE TITLE
nuster is not caching anyting, also it doesnt write in the disk

### ISSUE THREAD

**Issue by praveenkumar2608** [jiangwenyuan/nuster#59]
I am trying to cache, all the contents under / or /events. nuster is not caching any of the contents or write the same in in the disk.

**Nuster CFG** 

```
global
    log 127.0.0.1:514 local0 info
    log 127.0.0.1:514 local0 warning
    log 127.0.0.1:514 local0 notice
    nuster cache on data-size 1024m dir /var/www/cache uri /nuster/cache
    nuster nosql on data-size 1024m dir /var/www/nosql
    master-worker # since v3
    nbproc 1
    nbthread 2
    cpu-map auto:1/1-2 0-1
    # daemon
    # debug
    tune.ssl.default-dh-param 2048
defaults
    log global
    mode http
    option  httplog
    retries 3
    option redispatch
    timeout client  30s
    timeout connect 30s
    timeout server  30s
    errorfile 400 /var/log/haproxy/400.http
    errorfile 403 /var/log/haproxy/403.http
    errorfile 408 /var/log/haproxy/408.http
    errorfile 500 /var/log/haproxy/500.http
    errorfile 502 /var/log/haproxy/502.http
    errorfile 503 /var/log/haproxy/503.http
    errorfile 504 /var/log/haproxy/504.http

frontend events
    bind *:443 ssl crt /etc/nginx/ssl/testcdn.mycom1.com.pem
    mode http
    option forwardfor header X-Real-IP
    http-request set-header X-Real-IP %[src]
    http-request replace-header Host networks1.mycom1.com events.mycom.com
    reqadd X-Forwarded-Proto:\ https
    default_backend events

backend events
    mode http
    option forwardfor
    http-request replace-header Host networks1.mycom1.com events.mycom.com
    option http-buffer-request
    option httpchk GET /events HTTP/1.1\r\nHost:events.mycom.com
    nuster cache on
    #nuster rule r1 ttl 1d if pathA
    #nuster rule sync  disk sync  ttl 1d if { path_beg /backstatge/ }
    server events events.zoho.com:443 check ssl verify none

listen haproxy-monitoring
	bind *:80
        mode http
        stats enable
        #stats hide-version
        stats uri /haproxy?stats
        stats realm Strictly\ Private

```

**Nuster Cache output**

> curl http://127.0.0.1/nuster/cache
**GLOBAL**
global.nuster.cache.data.size: 1073741824
global.nuster.cache.dict.size: 1048576
global.nuster.cache.uri: /nuster/cache
global.nuster.cache.purge_method: PURGE
global.nuster.cache.stats.used_mem: 0
global.nuster.cache.stats.req_total: 54
global.nuster.cache.stats.req_hit: 0
global.nuster.cache.stats.req_fetch: 0
global.nuster.cache.stats.req_abort: 0

**PERSISTENCE**
global.nuster.cache.dir: /var/www/cache
global.nuster.cache.loaded: yes

>

**Comment by jiangwenyuan** [comment]
@praveenkumar2608 

```
#nuster rule r1 ttl 1d if pathA
#nuster rule sync disk sync ttl 1d if { path_beg /backstatge/ }
```
rule is commented out?

**Comment by praveenkumar2608** [comment]
Found the issue, path_peg URL goes like /backstage/view/profile/portal/6578921/siteresources/. The cahe get stored only if I give the entire URI. My requirement is to cache anything after /backstage/ because the URI after /Backstage/ changes based on user.

**Comment by packeteer** [comment]
why would it matter if /backstage/ gets included?

maybe tweak the cache key to be something like **method.uri** to match your use case better?

**Comment by praveenkumar2608** [comment]
I have tweaked it using method URI, now everything working as expected. **Is there any reason why GIF files not getting cached?** All jpeg and other files are getting cached properly

**Comment by packeteer** [comment]
can you show us an excerpt of the relevant config and log entires

**Comment by jiangwenyuan** [comment]
Close. Feel free to reopen if the problem persists.
