### ISSUE TITLE
support multiple config files

### ISSUE THREAD

**Issue by everyx** [jiangwenyuan/nuster#60]
**Is this a BUG report or FEATURE request?**:
FEATUER request

**What happened**:
multiple config files support

**What you expected to happen**:
Like nginx, we can put a site's config to a file, and put all config files to site-enable folder to enable it.

**Comment by packeteer** [comment]
do you mean built like a debian package?

**Comment by everyx** [comment]
> do you mean built like a debian package?

I just want we can use multiple config files to split my config.

I found haproxy can use -f multiple times, and can be a directory, so nuster has supported this?

**Comment by packeteer** [comment]
> I found haproxy can use -f multiple times, and can be a directory, so nuster has supported this?
yes, Nuster is based on Haproxy

**Comment by everyx** [comment]
great, just close.
