### ISSUE TITLE
Failing to cache HTTP/2 (and not showing cache stats)

### ISSUE THREAD

**Issue by llarsson** [jiangwenyuan/nuster#61]
**Is this a BUG report or FEATURE request?**:
BUG.

**What happened**:

Nuster does not seem to enable its caching for my HTTP/2 service, nor does it seem to expose its Cache management interface.

Trying to just read the cache endpoint:

```
$ curl http://localhost:9091/nuster/cache
<html><body><h1>503 Service Unavailable</h1>
No server is available to handle this request.
</body></html>
```

Nuster says:

```
<133>Jan 13 09:24:32 nuster[1]: Proxy waiter started.
<133>Jan 13 09:24:32 nuster[1]: Proxy stats started.
<133>Jan 13 09:24:32 nuster[1]: Proxy local_node started.
<133>Jan 13 09:24:32 nuster[1]: Proxy local_node started.
[NOTICE] 012/092432 (1) : New worker #1 (7) forked
<134>Jan 13 09:24:38 nuster[7]: 127.0.0.1:57126 [13/Jan/2020:09:24:38.476] stats stats/<NOSRV> -1/-1/-1/-1/0 503 216 - - SC-- 1/1/0/0/0 0/0 "GET /nuster/cache HTTP/1.1"
```

Also, even though my configuration says so, Nuster does not add any header, so I cannot think that it is caching.

**What you expected to happen**:

I want to:
 - cache HTTP/2 calls, regardless of method (GET or POST); and
 - enable the cache management interface, so that I can get some numbers about how caching is working.

**How to reproduce it (as minimally and precisely as possible)**:

This is my configuration file:
```
global
   maxconn 4096
   nuster cache on data-size 1024m dir /var/www/cache uri /nuster/cache
   log stdout local0 debug

defaults
   log   global
   mode http
   option httplog
   option http-use-htx
   timeout connect 10s
   timeout client 30s
   timeout server 30s
   maxconn 3000

frontend waiter
    bind *:9090 proto h2
    default_backend local_node

frontend stats
    bind *:9091
    stats enable
    stats uri /haproxy?stats


backend local_node
    log stdout local0 debug

    nuster cache on
    nuster rule all key method.scheme.host.uri.body etag on ttl 30 code all

    server localhost localhost:1337 proto h2
```

I start it using the following Docker command:

`docker run --rm --name nuster -v $(pwd)/nuster.cfg:/etc/nuster/nuster.cfg:ro --network host nuster/nuster:stable`

**Anything else we need to know?**:

N/A

**Environment**:
- OS: Ubuntu 18.04, but using Docker
- Kernel (e.g. `uname -a`): 5.0.0-37-generic #40~18.04.1-Ubuntu SMP
- Install tools:
- Others:

**Comment by packeteer** [comment]
I see 2 problems:
1. you need "option http-buffer-request" to cache POSTs
2. you have different locations declared for the stats uri

also, you might want to experiment with the htx option, the haproxy docs indicate it's still incomplete

**Comment by llarsson** [comment]
1. Tried adding it to the backend specification, and it did not make it work.
 2. Yes, this was intentional, as I assumed that Nuster's cache management functionality did not work over (cleartext) HTTP/2. Neither endpoint works.

The `option http-use-htx` option is needed for HTTP/2 functionality, at least, [for this particular use-case](https://www.haproxy.com/blog/haproxy-1-9-2-adds-grpc-support/).

**Comment by packeteer** [comment]
> 1. Tried adding it to the backend specification, and it did not make it work.

it works for me in default options

> 2. Yes, this was intentional, as I assumed that Nuster's cache management functionality did not work over (cleartext) HTTP/2. Neither endpoint works.

works for me when I have both uris the same, although I am not using http2

**Comment by llarsson** [comment]
@packeteer, could you please post your working configuration?

**Comment by jiangwenyuan** [comment]
nuster does not support htx yet, so backend http2 does not work. Will work in next version(upgraded to  haproxy v2.0).

Cache management interface indeed does not work in h2.

**Comment by llarsson** [comment]
Aha. Thank you, @jiangwenyuan.

How close are we to the next version, do you think?

**Comment by jiangwenyuan** [comment]
@llarsson Very slow development due to limited spare time these days, but I could make some time late this month and expect to release it next month

**Comment by jiangwenyuan** [comment]
@llarsson I failed to read `option http-use-htx` in your config file, that's the reason cache management API didn't work.
Again v3.2.0.19 only supports H2 between client and proxy, not proxy and backend(need htx).

**Comment by jiangwenyuan** [comment]
Released HTX version.
https://github.com/jiangwenyuan/nuster/releases/tag/v5.0.0.21
