### ISSUE TITLE
Nuster hangs every few hours

### ISSUE THREAD

**Issue by aleksystasiak** [jiangwenyuan/nuster#62]
**Is this a BUG report or FEATURE request?**:
BUG I think
**What happened**:
After a few hours of working properly, nuster hangs, Process is still being listed but stops listening for requests, restart will not work at this point, kill is needed.
**What you expected to happen**:
I expect nuster to keep working or at least leave some information about it's state in logs
**How to reproduce it (as minimally and precisely as possible)**:
Set ram only cache. Set data-size 7,5G. Give machine 10G ram total.
Use nuster as cache for site with quite big traffic, send all .jpg, .jpeg, .png, .css, js and .woff to nuster cache and wait few hours.
**Anything else we need to know?**:
Everytime ram used by machine where nuster runs goes up to ~4,25G - at this point nuster will freeze or restart
**Environment**:
- OS Debian Buster
- Kernel 4.9.0-4-amd64 #1 SMP Debian 4.9.65-3+deb9u1
- Install tools: nuster is compiled locally, standard haproxy systemd service is used to run nuster
- Others:
Nuster machine is virtual machine in Proxmox VE

**Comment by jiangwenyuan** [comment]
@aleksystasiak which version?

**Comment by aleksystasiak** [comment]
nuster version 3.2.1.19
Copyright (C) 2017-present, Jiang Wenyuan, <koubunen AT gmail DOT com >

HA-Proxy version 1.9.13 2019/11/25 - https://haproxy.org/

**Comment by aleksystasiak** [comment]
[
![Zrzut ekranu z 2020-02-03 10-48-04](https://user-images.githubusercontent.com/23705608/73642886-d27f5e00-4672-11ea-85f5-0705249c147f.png)
](url)
This illustrates hang frequency and ram usage.

**Comment by aleksystasiak** [comment]
`global
    maxconn 1000
#    debug
    nuster cache on data-size 8704m dict-size 1048576 uri /_nuster
    master-worker # since v3
    tune.maxrewrite 32768
    tune.bufsize 65536
#    dict-size 10485760
defaults
        mode http
        timeout connect     3s
        timeout client      3s
        timeout server     5s
        option forwardfor except 127.0.0.1
        option  httplog
        option  dontlognull
        retries 3
        option redispatch

frontend frontend_kids
        bind 172.16.34.12:80
        bind 127.0.0.1:80
        default_backend backend_kids
    http-response set-header x-cache-nuster hit if { nuster.cache.hit }
    acl at_least_one_cookie req.cook_cnt() gt 0
    http-request del-header Cookie if at_least_one_cookie
    http-request replace-header Cookie ssid=[^;]*;\s*(.*) \1
    http-request replace-header Cookie SID=[^;]*;\s*(.*) \1

backend backend_kids
        nuster cache on
# Mozna dywersyfikowac dlugosc cache dla sciezek
#    nuster rule img ttl 4d if { path_beg /images/ }
#    nuster rule api ttl 4d if { path /product_picture/ }
    nuster rule all ttl 4d
    http-response set-header x-cache hit if { nuster.cache.hit }
    stats enable
    stats uri /nstats
    stats auth nuster:stats
    server s1 172.16.34.201:80 check
    acl at_least_one_cookie req.cook_cnt() gt 0
    http-request del-header Cookie if at_least_one_cookie
    ignore-persist if at_least_one_cookie
    http-request replace-header Cookie ssid=[^;]*;\s*(.*) \1
    http-request replace-header Cookie SID=[^;]*;\s*(.*) \1
`

**Comment by jiangwenyuan** [comment]
@aleksystasiak fixed in master, int32 overflow due to big data-size(4gb). Could you please build master and recheck?
Thanks

**Comment by aleksystasiak** [comment]
Thank You for the fix. I will gladly test when I have opportunity ( unfortunately there were sporadic incidents with uncontrolled session switching when cache was enabled and now I have to deal with GDPR mess, but I'm negotiating reenabling the cache - not nuster fault In this case)
