### ISSUE TITLE
Purge cache problem (404 Error)

### ISSUE THREAD

**Issue by KelvinHuang1102** [jiangwenyuan/nuster#63]
**Is this a BUG report or FEATURE request?**:
Not sure.
**What happened**:
I'd like to purge cache but always get 404 Error
Here is my config
frontend cl
    bind *:8088	
    mode http
    default_backend pf
backend pf
    mode http    
    nuster cache on
    nuster rule all key method.scheme.host.uri.cookie_testcookie1    
    server s1 139.x.x.218:80	

I send HTTP request with cookie:
curl -v -X GET --cookie "testcookie1=1234" http://frontend_domain:8088/test/test.aspx
It cached successfully.
And then I want to purge cache:
curl -X PURGE -b "testcookie1=1234" http://frontend_domain:8088/test/test.aspx
It always shows 404 Not Found
But when I remove key setting
=> "nuster rule all"
The purge command worked and it return 200 OK

I was wondering if someone could give me some advice.

**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
**Environment**:
- OS (CentOS? Ubuntu?...)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 You need set `uri` in global like this:

```
global
nuster cache on uri /nuster/cache
```

then purge to this uri like this:

https://github.com/jiangwenyuan/nuster#cache-purging

If you `curl -X PURGE -b "testcookie1=1234" http://frontend_domain:8088/test/test.aspx`

default key is used. https://github.com/jiangwenyuan/nuster#purge-one-specific-url

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 You need set `uri` in global like this:
> 
> ```
> global
> nuster cache on uri /nuster/cache
> ```
> 
> then purge to this uri like this:
> 
> https://github.com/jiangwenyuan/nuster#cache-purging
> 
> If you `curl -X PURGE -b "testcookie1=1234" http://frontend_domain:8088/test/test.aspx`
> 
> default key is used. https://github.com/jiangwenyuan/nuster#purge-one-specific-url

If I send two different cookie in HTTP requests and I got  req_fetch: 2
1. curl -v -X GET --cookie "testcookie1=1234" http://frontend_domain:8088/test/test.aspx
2. curl -v -X GET --cookie "testcookie1=4321" http://frontend_domain:8088/test/test.aspx

Could I just purge specific one?

**Comment by jiangwenyuan** [comment]
Ah, not possible as of now

**Comment by KelvinHuang1102** [comment]
> Ah, not possible as of now
OK. I got it.
If the function could be enhanced.
It's will very helpful to me.  :)
Thanks for your quick reply.

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 It works now

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 It works now
@jiangwenyuan 
Thanks for your great support! It works!
