### ISSUE TITLE
Slow upload

### ISSUE THREAD

**Issue by Dragon988** [jiangwenyuan/nuster#64]
Hello!

I have an issue with slow upload. It's hitting a max of 1.5MB/s and I've verified with nginx reverse proxy it can hit over 20MB/s. I have tried disk and ram cache, no change.

Download speed is over 50MB/s.

I have also tried both the last official release and the master.

If you can give me some pointers much appreciated.

```
global
    tune.ssl.default-dh-param 2048
defaults
    mode http
    timeout connect 600s
    timeout client 600s
    timeout server 600s
    option http-buffer-request
frontend https-in
        bind *:443 ssl crt /root/nuster/certs/main.pem alpn h2,http/1.1
        acl host_drive hdr(host) -i blarg
        acl host_mail hdr(host) -i blarg
        use_backend mail_cluster if host_mail
        use_backend drive_cluster if host_drive
backend redirect_to_https
        redirect scheme https
backend drive_cluster
        server s1 192.168.5.3:100 check ssl verify none
        option forwardfor
backend mail_cluster
        server s2 192.168.5.2:444 check ssl verify none
        option forwardfor
frontend stats
        bind *:1991 ssl crt /root/nuster/certs/main.pem alpn h2,http/2
        stats enable
        stats hide-version
        stats uri /stats
        stats refresh 10s
        stats auth blarg
```

**Comment by jiangwenyuan** [comment]
@Dragon988 So you are using it as a load balancer?

**Comment by Dragon988** [comment]
Yes, that's correct. Load balancer with cache, which I disabled to troubleshoot.

**Comment by jiangwenyuan** [comment]
Have you tried set maxconn, etc?

**Comment by Dragon988** [comment]
No, but if it can hit 50MB/s when downloading a file it should be able to hit more then 1.5MB/s upload... I'll continue to look into HAProxy options along with nuster. Thank you for your time.

**Comment by jiangwenyuan** [comment]
try disable `http-buffer-request`?

**Comment by Dragon988** [comment]
Yes, same issue.

**Comment by jiangwenyuan** [comment]
Can you enable log? Maybe we can find something from the logs

**Comment by Dragon988** [comment]
It might actually be my host. I'll reopen this if it turns out not to be.

Thank you so much for the fast responses. I appreciate it!
