### ISSUE TITLE
Can not delete cache for domain? (nuster v5)

### ISSUE THREAD

**Issue by everyx** [jiangwenyuan/nuster#66]
Hi, i found that I cann't delete cache, when I send request below, I get 200 return by nuster, but cache for this domain not deleted, I can't find out what the problem is.

* nuster version: nuster docker v5.0.1.21

```shell
curl --request DELETE \
  --url https://example.com/_/nuster \
  --header 'host: example.com' \
  --header 'mode: cache'
```

my nuster config:

```
global
    nuster manager on uri /_/nuster purge-method PURGE
    nuster cache on data-size 50M dir /var/www/cache
    # nuster nosql on data-size 100m
    master-worker # since v3

resolvers docker
    nameserver dns1 127.0.0.11:53
    resolve_retries 3
    timeout resolve 1s
    timeout retry   1s
    hold other      10s
    hold refused    10s
    hold nx         10s
    hold timeout    10s
    hold valid      10s
    hold obsolete   10s

defaults
    mode http

    retries 3
    timeout client  30s
    timeout connect 30s
    timeout server  30s

    # remove forwardfor from haproxy
    option forwardfor except 10.0.0.0/8
    option forwardfor except 127.0.0.0/8

    default-server init-addr none

frontend http-in
    bind *:80

    acl cache_path path /_/nuster
    acl method_allow method DELETE
    http-request deny if cache_path !method_allow

    # set nuster cache header
    http-response set-header nuster-cache-status hit if { nuster.cache.hit }

    # user header host to resolve backend
    use_backend %[hdr(host)]

backend example.com
    nuster cache on

    nuster rule example memory on disk sync ttl 5m extend on if { res.hdr(content-type) -m beg -i text/html }

    server example  example:3000 resolvers docker init-addr none,libc
```

**Comment by jiangwenyuan** [comment]
@everyx Can you enable `debug` and upload the log? 

include: create the cache, get the cache, delete the cache, and get the cache again.

**Comment by jiangwenyuan** [comment]
@everyx You are using https: while `    bind *:80` ?

**Comment by jiangwenyuan** [comment]
Close for inactivity and irreproducible

**Comment by everyx** [comment]
> @everyx You are using https: while ` bind *:80` ?

Sorry about late reply, I have using  nuster behind traefik, `traefik(:443) -> nuster(:80) -> backend(:3000)`

> Can you enable debug and upload the log?
> include: create the cache, get the cache, delete the cache, and get the cache again.

Can I get you email address to send the log?

I have test if i remove traefik, and nuster get back worked fine, and this problem doesn't exist in v2.

**Comment by jiangwenyuan** [comment]
@everyx You can find the email in README or git log.

Since `nuster(:80) ` , so probably you need to use curl -X DELETE http:// instead of https:// depending on your config file. Can you share the config file? or remove scheme from key

https://github.com/jiangwenyuan/nuster#key-key

**Comment by everyx** [comment]
@jiangwenyuan email just sent with log and config file.

> Since nuster(:80) , so probably you need to use curl -X DELETE http:// instead of https:// depending on your config file. Can you share the config file? or try removing scheme from key

 I have auto https redirect, so I couldn't use `use curl -X DELETE http://`.
