### ISSUE TITLE
More sophisticated benchmarks?

### ISSUE THREAD

**Issue by icefoxen** [jiangwenyuan/nuster#7]
**Is this a BUG report or FEATURE request?**: Feature

**What happened**: I like your benchmarks, recently posted on lobste.rs, and I like your thoroughness in documenting your configs. However, would it be feasible to do something a bit bigger and/or more sophisticated than hello world?

**Comment by jiangwenyuan** [comment]
@icefoxen Hi, i'm very happy to do that. Anything concrete you are expecting? Any references, links to suck kind benchmarks would be help

**Comment by icefoxen** [comment]
Hi! The first things that come to mind are just larger data transfers and maybe small non-caching data (webapps, etc) to see how it does. I am not able expert on benchmarking http caches. :-)

**Comment by jiangwenyuan** [comment]
I see, I did do the test with large data (1k bytes), but as you can find [here](https://github.com/jiangwenyuan/nuster/wiki/Web-cache-server-performance-benchmark:-nuster-vs-nginx-vs-varnish-vs-squid#wrk-on-server129-cache-servers-on-server130-1gbps-bandwidth), reach the max throughput of the network when I test 256 bytes file. I only have 1Gb network, I certainly will do that if I have a 10Gb network.

I also did simply test to cache 1 million random requests, and benchmark, will write a new post about this later.

**Comment by jiangwenyuan** [comment]
Hi, I'm closing this, will add other benchmarks later
