### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by skinkie** [jiangwenyuan/nuster#73]
I'll run gdb next time, branch issue 69

[84343884.204634] traps: haproxy[20116] general protection ip:63515d sp:7ffc5a22b3e0 error:0 in haproxy[400000+2e4000]

**Comment by jiangwenyuan** [comment]
@skinkie Can you try on H2.1?

**Comment by skinkie** [comment]
@jiangwenyuan sure, did you merge issue 69 there?

**Comment by jiangwenyuan** [comment]
@skinkie yes

**Comment by skinkie** [comment]
@jiangwenyuan interesting or not, directly after restarting it in H2.1 I see a http2 protocol error ;-) Lets see how this continues.

**Comment by jiangwenyuan** [comment]
@skinkie fixed a segfault in H2.1, do not know if it's related or not though

**Comment by skinkie** [comment]
Restarted with the latest commit.

**Comment by skinkie** [comment]
Up till now no issues yet :)

**Comment by jiangwenyuan** [comment]
Thanks, I'm closing it, feel free to reopen if it happens again
