### ISSUE TITLE
cache key name by header response name

### ISSUE THREAD

**Issue by xjuggler** [jiangwenyuan/nuster#75]
Hi,

maybe it is my error. But I think not) I try to set the name of the cache entry by a header that I send on the source page.

```
acl resHdrCache res.hdr(CACHEKEY) -m found
nuster rule r1 key header_CACHEKEY memory off disk on ttl 30d if resHdrCache
```

The CACHEKEY is found and the site is cached. Problem is, that he not react afterword correctly. He is showing on every page the first site, which was cached by the key. For me it seems so, that he is not saving the cachekey or with empty string.

Best regards,

Stefan

```
global
    nuster cache on data-size 20000m dir /home/static_cache
    master-worker # since v3

    # intermediate configuration
    ssl-default-bind-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-bind-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-bind-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

    ssl-default-server-ciphers ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305:DHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384
    ssl-default-server-ciphersuites TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256
    ssl-default-server-options no-sslv3 no-tlsv10 no-tlsv11 no-tls-tickets

    ssl-dh-param-file /etc/nginx/dhparam.pem



defaults
    mode http
        timeout connect 6s
        timeout client  7s
        timeout server  8s
frontend fe
    bind *:8080 ssl crt /usr/local/nuster/ssl.pem alpn h2,http/1.1
    default_backend be1
backend be1
    nuster cache on
acl resHdrCache res.hdr(CACHEKEY) -m found
nuster rule r1 key header_CACHEKEY memory off disk on ttl 30d if resHdrCache

http-response set-header x-cache hit if { nuster.cache.hit }
http-response set-header x-key header_cachekey
server s1 fa.jeedoo.com:8081 ssl verify none

```

**Comment by jiangwenyuan** [comment]
@xjuggler This is expected behaviour. 

```
acl resHdrCache res.hdr(CACHEKEY) -m found
nuster rule r1 key header_CACHEKEY memory off disk on ttl 30d if resHdrCache
```
You an use response header `res.hdr(cachekey)` in ACL but not in key, the `header_cachekey` is only for request header

**Comment by xjuggler** [comment]
Thanks a lot for the fast reply. And keep up the great work! I think we will use your project for a project. 

Is there a way to set the key regarding the first response header? We would like to set the key in this way. This would make the handling of purging and refresh much more easy. Because we can not use the urls for that.

Best regards,

Stefan

**Comment by jiangwenyuan** [comment]
I don't think so. The key is used to look up the cache in the request stage to avoid sending requests to the backend, if we use the response header to set the key, only until we get the response could we know if it's a hit a not, so there's no point to cache.

**Comment by xjuggler** [comment]
I understand. Maybe a nice feature. If a header key is set, lookup in the key database if there is a cached entry. If not, request side and set cache with the header key. That would make the life so much easier. Maybe it would add a little to the first response, but i would not care. Because it is only the first response.

Should be possible from the logic side?

**Comment by jiangwenyuan** [comment]
I think it's impossible. suppose we have following two requests.

curl http://127.0.0.1:8080/something

and there are two different responses with different header_cachekey and we cached that.

Then next time when the same request comes, which one should we return?

So there's must be something in the request that cause a different response, then we can use that part as key.

**Comment by xjuggler** [comment]
I see. That's impossible) The problem is, I would like to purge by a key for an element of the site. But I have no idea, on which site this element was when set. We can purge a directory. But if there is a way to only purge 2 sites out of 100.000, it would be great. With setting a unique id via header, we could do that simply. But without, we need to save this in our database inclusive all the requested urls. And we can not change the urls or add something.

**Comment by jiangwenyuan** [comment]
Can you use rule name to purge?

```
acl resHdrCache res.hdr(CACHEKEY) -m found
nuster rule ruleResHdrCacheKey memory off disk on ttl 30d if resHdrCache
```

With above rule, if cachekey is found in response header, then the response is cached.

And you can use rule name `ruleResHdrCacheKey` to purge that.

**Comment by xjuggler** [comment]
I need to delete specific keys. They are all unique. Have to check the documentation, if I can regex the header values. But I think you understand the problem. But please, do not waste you time. That is our homework) But I'm glad you response that fast and help us)

**Comment by jiangwenyuan** [comment]
I'm closing it, feel free to open new issues if you have any problems:)
