### ISSUE TITLE
Respect ttl from the cache-headers

### ISSUE THREAD

**Issue by igorescobar** [jiangwenyuan/nuster#77]
## Current behavior
`Nuster` ignores the information ta comes from the backend regarding for how long should Nuster cache the file. It means that if your backend already takes care of setting correctly the `Cache-Control` header you might have to duplicate all your cache definitions in both places since this header is highly adopted if you have a CDN on top of your service or even for local caching on the user browser.

## Expected Behaviour
Currently, the only way we have to tell how for how long `Nuster` should cache our files is by using the `ttl=<time>`. 

In my humble opinion, the default should be to respect what is defined on the HTTP protocol (honoring the headers) and gives us the option to tell otherwise as `Nginx` does. But I guess this might be a harder decision to make. So in that case, it would be nice if `ttl` accepted an option like `ttl=auto` or similar. Where `ttl=auto` means it will use that's defined on the backend response.

Thanks a lot and keep it up with the good work! 🏆

**Comment by jiangwenyuan** [comment]
Added

**Comment by igorescobar** [comment]
Nice!

**Comment by igorescobar** [comment]
When will it be available via Docker?

**Comment by jiangwenyuan** [comment]
The `latest` image is building on Dockerhub. Note that it's based on `master` branch.
