### ISSUE TITLE
Clean files that are not requested for x period of time.

### ISSUE THREAD

**Issue by igorescobar** [jiangwenyuan/nuster#78]
## Current Behavior
`Nuster` do not clean inactive files. It means that I might set a cache policy for that file that might make them being cached for months by default. For services that deal with millions of files this might mean a lot of money wasted on files that are not requested/needed anymore.

## Expected Behavior
`Nginx` offers a parameter called `inactive=` on the proxy_cache_path directive:
```
proxy_cache_path /path/to/cache levels=1:2 keys_zone=my_cache:10m max_size=10g inactive=60m use_temp_path=off;
```

What "inactive" does is:
> Cached data that are not accessed during the time specified by the inactive parameter get removed from the cache regardless of their freshness. By default, inactive is set to 10 minutes.

So even though the file ttl is 6 months, it will still delete the file from the cache folder if they file isn't accessed for `60m` in that case.

**Comment by jiangwenyuan** [comment]
Added.
