### ISSUE TITLE
CPU Getting Higher and Higher

### ISSUE THREAD

**Issue by igorescobar** [jiangwenyuan/nuster#84]
Ever since I started using Nuster the CPU usage keeps getting higher and higher and the "age" of the container gets older.

So this is the traffic on the last day:
![Screenshot 2020-05-25 at 12 17 24](https://user-images.githubusercontent.com/24032/82808486-fcf36200-9e81-11ea-917b-5ca341887ae7.png)

This is the number of containers (a new container gets added every time the CPU hits >50%:
![Screenshot 2020-05-25 at 12 16 37](https://user-images.githubusercontent.com/24032/82808542-15fc1300-9e82-11ea-914d-70c69866c7d3.png)

And this is the CPU consumption:
![Screenshot 2020-05-25 at 12 15 49](https://user-images.githubusercontent.com/24032/82808580-2b713d00-9e82-11ea-97f5-98cd8a943861.png)

This is the cache stats:
![Screenshot 2020-05-25 at 12 22 00](https://user-images.githubusercontent.com/24032/82808677-58bdeb00-9e82-11ea-9837-aa650656b192.png)

So the biggest portion of the traffic is being served directly via Nuster because it's cached so that makes it pretty weird.

As of comparison... this is the usual CPU & memory usage on this application (with Nginx):
![Screenshot 2020-05-25 at 12 24 17](https://user-images.githubusercontent.com/24032/82808861-c1a56300-9e82-11ea-8ea7-050ac30f05a0.png)

And this is the CPU & Memory usage by Nginx alone
![Screenshot 2020-05-25 at 12 25 53](https://user-images.githubusercontent.com/24032/82808925-e39ee580-9e82-11ea-85fd-6084de0e54c6.png)

The problem is that with this behavior I need to be manually replacing the containers and the CPU just keeps getting higher and higher as I add more containers. The "normal" should be as I add more containers the CPU should lower and not keep increasing :(

**Comment by igorescobar** [comment]
Look how much the CPU decreases if I just replace the all the 5 containers by 2 (completely new containers):
![Screenshot 2020-05-25 at 12 37 46](https://user-images.githubusercontent.com/24032/82809673-8b68e300-9e84-11ea-83d3-e4b569ff85e3.png)

The CPU goes back to the normal levels and the traffic is exactly the same.

**Comment by igorescobar** [comment]
Still too soon to tell but seems like removing the `disk-loader 100000` might have fixed it. You said that it wouldn't make any difference 😄 .

I will keep an eye for a few more hours, let's see.

**Comment by igorescobar** [comment]
The only issue that happened so far after disabling this is:
```
15
2020-05-25T13:55:13.669+01:00
[NOTICE] 145/125513 (1) : haproxy version is 2.2-dev8
16
2020-05-25T13:55:13.669+01:00
[NOTICE] 145/125513 (1) : path to executable is /usr/local/sbin/nuster
17
2020-05-25T13:55:13.669+01:00
[ALERT] 145/125513 (1) : Current worker #1 (8) exited with code 139 (Segmentation fault)
18
2020-05-25T13:55:13.669+01:00
[ALERT] 145/125513 (1) : exit-on-failure: killing every processes with SIGTERM
19
2020-05-25T13:55:13.669+01:00
[WARNING] 145/125513 (1) : All workers exited. Exiting... (139)
```

Just about 1h after deploying the change.

**Comment by jiangwenyuan** [comment]
Let's see what happens on v5.0.10.21

**Comment by igorescobar** [comment]
I'm deploying it right now. But the CPU issue seems to be resolved by removing the flag.

**Comment by igorescobar** [comment]
1) It has been running for a few hours now. Removing the disk-loader with a bug number seems to have fixed the issue so there is definitely room for improvement there. 

2) Now that the CPU is more stable the number of containers needed will be also more steady, it means that I will be able to monitor how Nuster performs after running several hours and see if any crazy crash occurs.

**Comment by igorescobar** [comment]
One day running. No issues. 

About the `disk-loader` is it a bug? The CPU was getting higher and higher as the number of cached items increased. You mentioned that it wouldn't matter to set it as a high number as the timeout was `10ms`.

For what is worth, Nginx implements 3 flags that you can control:
`loader_files=100 loader_threshold=200 loader_sleep=50`

You can read more about there here: http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_cache_path

**Comment by jiangwenyuan** [comment]
It might not relate to disk-loader. I did not observe this kind of behaviours.

Currently I use haproxy main loop to load cache file which has a 1 second limit. I'm looking into haproxy task, might use task to reimplement that, or use linux async io to do that.

**Comment by igorescobar** [comment]
> Currently I use haproxy main loop to load cache file which has a 1 second limit. 

Yeah I noticed that from the source. The only problem is it causes major performance issues when the number is too high and using the full second to load files.

> I'm looking into haproxy task, might use task to reimplement that, or use linux async io to do that.

Using a `task/jobs` approach is similar to what Nginx does I suppose. Every type of `task` has a different level of "priority" and it doesn't "block" the rest of the incoming requests at least not for too long. Using a async approach might also bring good results but I would say that if HAProxy already has something implemented to help with that might be good to use it.

**Comment by igorescobar** [comment]
The way it's currently implemented my cache will never be loaded into memory as it is already 50GiB+ and loading into chunks off 100 files will take forever. By the time we are 50% loaded the auto-scaling kicks in and it starts all over again.

**Comment by packeteer** [comment]
I think Varnish would suit your use case better
https://info.varnish-software.com/blog/varnish-mse-persistence

**Comment by jiangwenyuan** [comment]
> Yeah I noticed that from the source. The only problem is it causes major performance issues when the number is too high and using the full second to load files.

No, it won't.

> Using a task/jobs approach is similar to what Nginx does I suppose. Every type of task has a different level of "priority" and it doesn't "block" the rest of the incoming requests at least not for too long. Using a async approach might also bring good results but I would say that if HAProxy already has something implemented to help with that might be good to use it.

It is done in master process, neither the task implementation nor current implementation would block incoming requests.

It's only using async disk IO to load cache file instead of current pread/pwrite, it has nothing to do with haproxy.

> The way it's currently implemented my cache will never be loaded into memory as it is already 50GiB+ and loading into chunks off 100 files will take forever. 

The whole cache won't be loaded into memory. Only path info and some key info.

> By the time we are 50% loaded the auto-scaling kicks in and it starts all over again.

I doubt that disk-loader caused this 50% cpu. I never observed a cpu usage greater than 10% of master nuster process which does the load stuff.

**Comment by igorescobar** [comment]
> I think Varnish would suit your use case better
https://info.varnish-software.com/blog/varnish-mse-persistence

Thanks @packeteer. I've used Varnish in the past, many years ago and I didn't look it up ever since.

Nuster caught my attention initially with their benchmarks up to 3x faster than Nginx etc., and after looking at the caching mechanism a decided to give it a go mostly to see how the MISS/HIT rate would perform compared with Nginx and not really because of the performance claim. 

So far the MISS/HIT rate is way better mostly because `Nuster` tries to find the file on disk during the "load into memory" period and this avoids a lot of "MISS" during the container initialization and this is great. Performance-wise, in my case, it's actually slower or equal, even when the file is cached. Let's see if there is any fine tunning missing.

As far as I understood, the amount of files cached shouldn't matter as they are gradually loaded into memory and we can easily load millions of files into the hash table with very little memory allocated so, at this point, I would only check Varnish out to see how it performs especially on the TTFB area.

@jiangwenyuan 
> It is done in master process, neither the task implementation nor current implementation would block incoming requests.

I didn't say it would, I made a comment in general. You said on your comment `I'm looking into haproxy task` so I thought it was related to HAProxy sorry if I miss understood your statement.

> The whole cache won't be loaded into memory. Only path info and some key info.

I know, this is what I meant. Even when loading only the hash table, since it takes many hours to complete the full load into the hash table, on my case, it never happens because the auto-scaling triggers all the time and it has to start all over.

> I doubt that disk-loader caused this 50% cpu. I never observed a cpu usage greater than 10% of master nuster process which does the load stuff.

How much traffic are you testing your `Nuster` cluster against and how big is your cache folder?

**Comment by jiangwenyuan** [comment]
@igorescobar 

I only use `memory on` mode for all my envs. I have a test env with 1.5 million cache files of total 40GB size. I use wrk lua script to load test.

The master process is basically 0.x% cpu. There must be other factors caused the increased cpu usage.

**Comment by igorescobar** [comment]
@jiangwenyuan 
I see. I'm curious to see how would it perform with `disk-loader 100000` and `memory off disk on` and with continuous traffic stream + 2k per minute during 1+ hours.

**Comment by jiangwenyuan** [comment]
@igorescobar So I did some test with 2 identical servers:

## srv-nuster

```
                --| nuster 01 :3001    |--
               /                           \
              /                             \
-------------                                ------------------
haproxy :6000                                nginx origin: 8000
-------------                                ------------------
              \                             / 
               \                           /
                 --| nuster 02 :3002    |--
```

nuster 01 and nuster 02 are using `/cachedata/nuster` as disk directory

## srv-nginx

```
                --| nginx  01 :3001    |--
               /                           \
              /                             \
-------------                                ------------------
haproxy :6000                                nginx origin: 8000
-------------                                ------------------
              \                             / 
               \                           /
                 --| nginx 02 :3002    |--

```
nginx 01 and nginx 02 are using `/cachedata/nginx` as disk directory


## config file

### nuster

```
global
  maxconn 100000
  nuster cache on data-size 1g dict-size 100m dir /cachedata/nuster disk-loader 987654
  nuster manager on uri /nuster
  master-worker
defaults
  mode http
  option http-keep-alive
  retries 1
  option redispatch
  timeout http-keep-alive  72s
  timeout client           72s
  timeout connect          72s
  timeout server           72s
frontend fe
  bind *:3001
  default_backend be
backend be
  nuster cache on
  nuster rule r0 memory off disk on ttl 12d
  http-response set-header x-cache HIT if { nuster.cache.hit }
  server s1 127.0.0.1:8000
```
nuster1.cfg uses 3001 and nuster2.cfg uses 3002

### nginx

```
worker_processes  1;
worker_rlimit_nofile 100000;
error_log  /tmp/nginx/error1.log warn;
pid        /tmp/nginx/nginx1.pid;
events {
  worker_connections  100000;
  use epoll;
  multi_accept on;
}
http {
  include                     /etc/nginx/mime.types;
  default_type                application/octet-stream;
  access_log                  off;
  sendfile                    on;
  server_tokens               off;
  keepalive_timeout           300;
  keepalive_requests          100000;
  tcp_nopush                  on;
  tcp_nodelay                 on;
  client_body_buffer_size     128k;
  client_header_buffer_size   1m;
  large_client_header_buffers 4 4k;
  output_buffers              1 32k;
  postpone_output             1460;
  proxy_cache_path /cachedata/nginx levels=1:2 keys_zone=STATIC:100m inactive=2d;
  server {
    listen 3001;
    location / {
      proxy_pass        http://127.0.0.1:8000/;
      proxy_cache       STATIC;
      proxy_cache_valid any 12d;
    }
  }
}
```
nginx1.cfg uses 3001 and nginx2.cfg uses 3002

## wrk script

```
local urls = {
  "/images/aaa.jpg",
  "/images/aab.jpg",
  "/images/aac.jpg",
  -- ... 50 jpg files with random size
}

math.randomseed(os.time())

local i = 1
request = function()
    local r = math.random(1, 1000000)
    if i > 50 then
        i = 1
    end
    local url = urls[i] .. "?r=" .. r
    i = i + 1
    return wrk.format(
    'GET',
    url
    )
end
```

Since the query is used as cache key, we can cache lots of files, although there are only 50 origin files.

```
wrk -c 10 -d 10000 -t 10 -s test.lua http://127.0.0.1:6000
```

### nuster

```
Running 167m test @ http://127.0.0.1:6000
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    11.38ms   23.53ms   1.06s    94.47%
    Req/Sec   171.42     79.88   790.00     67.54%
  16974329 requests in 166.67m, 376.66GB read
Requests/sec:   1697.42
Transfer/sec:     38.57MB
```

### nginx

```
Running 167m test @ http://127.0.0.1:6000
  10 threads and 10 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    54.84ms  146.45ms   2.00s    94.04%
    Req/Sec    72.35     86.40     0.87k    90.97%
  5729051 requests in 166.67m, 127.06GB read
  Socket errors: connect 0, read 0, write 0, timeout 2752
Requests/sec:    572.90
Transfer/sec:     13.01MB
```
And the cpu of nuster is pretty steady.

![image](https://user-images.githubusercontent.com/19603306/83000856-e564d680-a045-11ea-8dff-656ef25a44bd.png)

**Comment by igorescobar** [comment]
Thanks a lot for putting this together @jiangwenyuan! 

What about the Nginx CPU?

**Comment by jiangwenyuan** [comment]
@igorescobar updated

**Comment by igorescobar** [comment]
What if you do the same test with the disk-loader using the default value of 100?

But this pretty much exemplifies what happened to me. The base CPU of the ECS task increased a lot and when I disabled removed the `disk-loader` flag the CPU when back to the normal levels.

**Comment by igorescobar** [comment]
If you do this test you might be able to see how much CPU the `disk-loader` can consume if set with a big number like 100k files per cycle.

**Comment by igorescobar** [comment]
For me, the difference in CPU usage with and without the flag was huge and I wasn't expecting it to consume that much CPU.

**Comment by jiangwenyuan** [comment]
May because the env is different. I started two nuster processes in VM, and using local disk directory directly.
And you are using docker and EFS? Are you able to confirm this in VM?

**Comment by igorescobar** [comment]
In my case, all containers start in different VMs they are not inside the same machine. Amazon ECS Fargate is like a "container as a service" and they do not run your containers inside of EC2 instances like the previous generation. And all these containers are pointing to the same /nuster/cache EFS volume. We could say that it could be an EFS limitation or something but the % I/O limits never went above 18% and after a few minutes of the container initialization it goes way above de 5% line.

**Comment by jiangwenyuan** [comment]
I understand. I assume EFS is sort of net base, while nuster process and disk in my test reside in same VM.

> Did you run the performance test with the disk-loader 100 (default) and the CPU usage was the same?

Yeah, same CPU usage so far.

**Comment by jiangwenyuan** [comment]
Close for unreproducible
