### ISSUE TITLE
Disk sync problem (no cache data sync to disk)

### ISSUE THREAD

**Issue by KelvinHuang1102** [jiangwenyuan/nuster#87]
I try to configure my rule to sync cache to disk
When I enable this function, I can't find any cache file in the path.
Not sure what's going on, would you please give me some advice? thanks.

## What's the configuration?

global    
    nuster manager on uri /nuster/cache
    nuster cache on data-size 200m dir /usr/local/nuster/cache
     ...
backend bk
     nuster rule r1 disk sync memory on key method.scheme.uri.cookie_SessionId if { path /xxx/ }
     nuster rule r2 disk sync memory on key method.scheme.uri if { path_beg /xxx/ooo }
 
## Steps to reproduce the behavior
     I send request to nuster and it cached normally, but I didn't found any cached data in my dir path.

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 Cache data are not saved to disk immediately in disk sync mode. The cache data are saved to memory and will be saved to disk by master process sometime later.

If you need data saved to disk immediately, you can use `disk on` mode

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 Cache data are not saved to disk immediately in disk sync mode. The cache data are saved to memory and will be saved to disk by master process sometime later.
> 
> If you need data saved to disk immediately, you can use `disk on` mode

But I wait for a long time(yesterday to this morning), I still can't see any cached file.
Is need any criteria to trigger this action?

**Comment by KelvinHuang1102** [comment]
By the way, if I use disk on mode. Is that mean the cache will save to disk only? or it will also save in memory both?

**Comment by jiangwenyuan** [comment]
I see. Can you confirm that the data is cached (in memory)? You can check that by `http-response set-header x-cache hit if { nuster.cache.hit }
` 
> By the way, if I use disk on mode. Is that mean the cache will save to disk only? or it will also save in memory both?

`memory on disk off`: save to memory only
`memory on disk on`: save to both memory and disk
`memory off disk on`: save to disk only
`memory on disk sync`: save to memory and sync to disk later

**Comment by KelvinHuang1102** [comment]
I set "memory on disk on", but I got another problem.
I create a cache first and cache file also created.
Then I restart nuster , I try to PURGE cache , it seems not work.
After I send PURGE command and got 200 response but cache still exist!
How can I PURGE cache in disk?

**Comment by jiangwenyuan** [comment]
> Purging cache files by proxy name or rule name or host or path or regex only works after the disk loader process is finished. You can check the status through stats url.

**Comment by KelvinHuang1102** [comment]
Do you mean these info?
**DICT**
dict.cache.size:                   1048576
dict.cache.length:                 131072
dict.cache.used:                   1
dict.cache.cleanup_idx:            50000
dict.cache.sync_idx:               4900
**STORE DISK**
store.disk.cache.dir:              /home/ubuntu/cache
store.disk.cache.loaded:           yes

I check stats , it seems already loaded. But I can't PURGE cache in disk.
I Purge it by path and always got 200 response but cache still exists.

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 Can you enable debug in config or add `http-response set-header x-cache hit if { nuster.cache.hit }` and do following:

```
curl -v http://ip/path/to/your/file # this should create the file
curl -v http://ip/path/to/your/file # to confirm is the cache is created or not
restart nuster
curl -v http://ip/path/to/your/file # to confirm is the cache is created or not again
curl -XDELETE or -XPURGE your full command
```

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 Can you enable debug in config or add `http-response set-header x-cache hit if { nuster.cache.hit }` and do following:
> 
> ```
> curl -v http://ip/path/to/your/file # this should create the file
Yes... cache file created
> curl -v http://ip/path/to/your/file # to confirm if the cache is created or not
Yes...  debug screen shows :  HIT memory
> restart nuster
> curl -v http://ip/path/to/your/file # to confirm if the cache is created or not again
yes... debug screen shows: HIT disk
> curl -XDELETE or -XPURGE your full command
return 200 OK
> ```
And then I send my URL again, the debug screen still shows HIT disk
It's very strange.

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 can you show me the purge command? And before you do the purge command can you confirm the load is completed?

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 can you show me the purge command? And before you do the purge command can you confirm the load is completed?

my rule:
nuster rule r1 disk sync memory on key method.scheme.uri.cookie_SessionId if { path /xx/Form.aspx }

send request:
curl -k -v -X GET -u "acc":"pwd" --cookie "SessionId=12345" "https://domain/xx/Form.aspx"

purge command:
curl -k -X PURGE --cookie "SessionId=12345" https://domain/xx/Form.aspx

How to make sure load is completed?

my version:
--------------------------------------------------------------------------------
ubuntu@ip-172-31-54-89:/usr/local/nuster$ /usr/local/nuster/sbin/nuster -v
nuster version 5.0.10.21
Copyright (C) 2017-present, Jiang Wenyuan, <koubunen AT gmail DOT com >
HA-Proxy version 2.1.4 2020/04/02 - https://haproxy.org/
Status: stable branch - will stop receiving fixes around Q1 2021.
Known bugs: http://www.haproxy.org/bugs/bugs-2.1.4.html

**Comment by jiangwenyuan** [comment]
Since you are using basic purge not advanced purge, there's no need to check load.

Let me check.

**Comment by KelvinHuang1102** [comment]
> Since you are using basic purge not advanced purge, there's no need to check load.
> 
> Let me check.

OK, thanks!

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 Fixed, can you use latest H2.1 branch and confirm? Thanks

**Comment by KelvinHuang1102** [comment]
> @KelvinHuang1102 Fixed, can you use latest H2.1 branch and confirm? Thanks

Should I download this version again?
https://github.com/jiangwenyuan/nuster/releases/download/v5.0.10.21/nuster-5.0.10.21.tar.gz

**Comment by jiangwenyuan** [comment]
You can git clone the repo and checkout H2.1, or use this link:
https://github.com/jiangwenyuan/nuster/archive/H2.1.zip

**Comment by KelvinHuang1102** [comment]
> You can git clone the repo and checkout H2.1, or use this link:
> https://github.com/jiangwenyuan/nuster/archive/H2.1.zip

This version worked!  Thanks for your quickly support.

**Comment by jiangwenyuan** [comment]
@KelvinHuang1102 Thanks a lot for reporting:)
