### ISSUE TITLE
性能描述有问题

### ISSUE THREAD

**Issue by myselfghost** [jiangwenyuan/nuster#9]
![nuster](https://user-images.githubusercontent.com/16330754/37023150-fa4c7c0e-215f-11e8-9ebe-bddcd808d730.png)

在实际生产环境中，显然是1K 或者大于1K的场景，那么从数据来看看明明是接近的性能，为什么是2倍，3倍？

**Comment by jiangwenyuan** [comment]
@myselfghost 这是带宽已经打满的情况，所以差不多。因为只有1gbps的带宽，在文件超过256字节时带宽就打满了。如果有10gbps的网络的话可以试一下。
