### ISSUE TITLE
nuster 5.2.0.22 crashed by SIGSEGV

### ISSUE THREAD

**Issue by slw** [jiangwenyuan/nuster#90]
nuster 5.2.0.22 crashed by SIGSEGV at currently unknow condition.

(gdb) bt
#0  0x00000000005c96e7 in _nst_cache_filter_http_headers (s=0x3806a3c400, filter=0x380bffe100, msg=0x38113e91f0) at src/nuster/cache/filter.c:158
#1  0x00000000004c62b5 in flt_analyze_http_headers (s=0x3806a3c400, chn=0x3806a3c410, an_bit=16384) at src/filters.c:770
#2  0x000000000041e2bb in process_stream (t=0x38113e9140, context=0x3806a3c400, state=260) at src/stream.c:1787
#3  0x0000000000568a96 in run_tasks_from_lists (budgets=0x7fffdfbfbe0c) at src/task.c:476
#4  0x0000000000569992 in process_runnable_tasks () at src/task.c:674
#5  0x00000000004ee785 in run_poll_loop () at src/haproxy.c:2953
#6  0x00000000004f47d2 in run_thread_poll_loop (data=0x2) at src/haproxy.c:3120
#7  0x00000008006ef736 in ?? () from /lib/libthr.so.3
#8  0x0000000000000000 in ?? ()
Backtrace stopped: Cannot access memory at address 0x7fffdfbfc000

`            ctx->rule = nuster.proxy[px->uuid]->rule;
 
            for(i = 0; i < ctx->rule_cnt; i++) {
                int  idx = ctx->rule->key->idx;
`

(gdb) p px->uuid
$7 = 4
(gdb) p *nuster.proxy[px->uuid]
$5 = {rule = 0x0, key = 0x0, rule_cnt = 1, key_cnt = 0}

**Comment by jiangwenyuan** [comment]
@slw Thanks for the report, can you share the config file?

**Comment by slw** [comment]
> @slw Thanks for the report, can you share the config file?

I am currently attach gdb to faulted process and can do query/inspect.
I am don't know what request is (may be some botnet scaning this ip)

`
global
        master-worker
        maxconn 81920
        nuster cache on data-size 192g
        nuster manager on uri /X/X purge-method MYPURGE
        tune.maxaccept -1
        tune.ssl.default-dh-param 2048
        tune.h2.max-concurrent-streams 8000
        nbproc 1
        nbthread 20
        cpu-map auto:1/1-20 0-19
        log /dev/log local0
        stats socket /var/run/haproxy.sock
        user www
        group www
        daemon

defaults
        mode http
        log global
        http-reuse always
        option http-keep-alive
        option httplog
#       option dontlognull
        option redispatch
        retries 3
        maxconn 80000
        backlog 4096
        timeout connect 5000
        timeout client 50000
        timeout server 50000

frontend stats
        bind *:X
        stats enable
        stats uri /haproxy?stats
        stats refresh 10s
        stats admin if LOCALHOST
        stats realm HAProxy\ Statistics
        stats auth X:X

frontend live
        mode http
        bind :80 backlog 1024 name clear
        bind :443 ssl crt /usr/local/etc/nginx/ssl/ backlog 1024 name clear
#       option dontlog-normal
        http-request del-header ^X-Forwarded-For:.*
        option forwardfor
#       option dontlognull
#       monitor-uri /monitoruri
        maxconn 80000
        default_backend live

backend live
        mode http
        timeout connect 5s
        timeout server 5s
        nuster cache on
#       nuster rule all ttl 0
        nuster rule cacheRule ttl auto
# When auto is used, the ttl is set to the value of s-maxage or max-age directive in the cache-control header.
        server live1 XXX:80
`

**Comment by jiangwenyuan** [comment]
@slw Thanks, fixed in master branch.
