### ISSUE TITLE
How to Install and Configure Nuster on CentOS 8 WordPress?

### ISSUE THREAD

**Issue by bestpaydeals** [jiangwenyuan/nuster#92]
Hi,
I want to try Nuster web cache on my CentOS 8 VPS with WordPress running on NGINX. Please help me get any tutorial about How to install and configure Nuster on CentOS 8 NGINX with WordPress?

Varnish is like hair pulling and I am not able to make it work properly as I am trying from 1 year on my SSL site. Now, I see Nuster as a good hope!

Thank you.

**Comment by jiangwenyuan** [comment]
Hi,

After  you download the source, run 

```
dnf install gcc make
make TARGET=linux-glibc
```

For other build options, see https://github.com/jiangwenyuan/nuster/blob/master/INSTALL

**Comment by bestpaydeals** [comment]
I will try building options. But, isn't it's possible to install from repo or rpm package? Also, I am in need of full configuration tutorial for WordPress website on CentOS if possible. Thanks!

**Comment by jiangwenyuan** [comment]
No, there's no rpm packages.

You can check this example: https://github.com/jiangwenyuan/nuster/wiki/Use-nuster-As-HTTP-Cache-Server

**Comment by packeteer** [comment]
just as an alternative, there are caching plugins for Wordpress. Have you
tried them?

**Comment by bestpaydeals** [comment]
Yes I am using cache plugin. However, I believe that Nuster will speed up more. I want to use cache from server side not from WP. So, I would like to see how Nuster goes.
