### ISSUE TITLE
How does Nuster serve stale cache responses?

### ISSUE THREAD

**Issue by sigginet** [jiangwenyuan/nuster#96]
After a bit of trial and error, I've managed to set up a caching proxy using Nuster.

When I'm testing the cache and the stale data functionality, I am unsure of how the stale data functionality works.

I expected the functionality to be `stale-while-revalidate`, but it appears to be `stale-if-error` from what I am experiencing in my tests.

Here's a bit of info on both types: https://tools.ietf.org/html/rfc5861#section-1

@jiangwenyuan of the two modes below, which one does Nuster use?

TL;DR - The difference is that if the cache TTL expired, the client will still receive stale cache quickly and the server will refresh in the background.

## Stale-while-revalidate mode:
![image](https://user-images.githubusercontent.com/1608474/90641304-9b445900-e220-11ea-93b7-0c10e640b5a5.png)

## Stale-if-error mode:
![image](https://user-images.githubusercontent.com/1608474/90641083-55879080-e220-11ea-9027-67992c345f3b.png)

Sorry if the images are a bit cluttered - It's as clear as I could make it in a quick manner

**Comment by sigginet** [comment]
NGINX has a similar functionality with background refresh: https://www.nginx.com/blog/nginx-caching-guide/#Fine%E2%80%91Tuning-the-Cache-and-Improving-Performance

You need to use these two directives:
```
proxy_cache_use_stale updating;
proxy_cache_background_update on;
```

**Comment by jiangwenyuan** [comment]
@sigginet 

Let's say we have a cached response of request `/test`, which has a ttl of 100 seconds.

After 100 seconds, the cache is expired(assume no `extend`). 

Suppose request A '/test' comes in at 101 seconds, another request B comes in at 102 seconds, and request C comes in at 110 seconds. (Assume backend needs 5 seconds to handle the request)

1. `use-stale off`

A will be forwarded to backend and the cache will be updated.
B will be either forwarded to backend(on `wait`), or wait for ever(`wait on`) or some time(`wait TIME`)
C will be served use the new cache

2. `use-stale on`

A will be forwarded to backend and the cache will be updated.
B will be served use the stale cache
C will be served use the new cache

3. `use-stale 3`

same as 2

Let's say during the handling of A, the backend is down.

1. `use-stale off`

A/B/C will fail

2. `use-stale on`

A will fail while B and C will be served use the stale cache

3. `use-stale 3`

A will fail, B will be served use the stale cache, but C will fail as the stale cache is valid only for 3 seconds.

**Comment by sigginet** [comment]
Thanks for the clarification @jiangwenyuan 

We're adding a cache where we want to pre-cache a lot of data, but each entry will not be hit often at the same time, so it's likely that very few requests (<1%) will receive the stale cache after TTL expires.

Is there a way for me to trigger a cache update manually with a key or something before the TTL expires?

**Comment by jiangwenyuan** [comment]
@sigginet No, not as of now..I have plan to extend haproxy lua to support more cache functionalities, this one could be a good candidate.

But why do you need to do that, is that any other way to achieve what you really want?

**Comment by sigginet** [comment]
@jiangwenyuan I need this to preload cache and then serve stale cache responses to the users while updating silently in the background.

The preloaded entries will result in 90% of entries never getting hit.

I could achieve this by aggressively precaching, but that will just be a waste of server resources on our end and other backends.

The goal is to have a fast user experience for all the most likely user queries

**Comment by boldtrn** [comment]
To add a +1, I am also looking to server stale content while updating in the background. From the docs it's not really clear that this does not work with the serve stale setting.

**Comment by interlinked** [comment]
Also +1 for stale-while-revalidate functionality.
